rubyonjets/jets

lib/jets.rb, lib/jets/booter.rb, lib/jets/commands/deploy.rb, lib/jets/core.rb, lib/jets/core_ext/kernel.rb, lib/jets/io.rb, lib/jets/logger.rb, lib/jets/ruby_server.rb
* improve handling of puts override
=> Jets::IO and Kernel overrides for puts

docs/_docs/crud-json-dynamodb.md, docs/_docs/next-steps.md, docs/_includes/subnav.html, docs/faq.md, lib/jets/controller.rb, lib/jets/controller/base.rb, lib/jets/controller/rendering.rb, lib/jets/controller/response.rb, spec/fixtures/dumps/api_gateway/stores/index.json, spec/lib/jets/controller/base_spec.rb, spec/lib/jets/controller/response_spec.rb
=> support setting response headers for cookies

Gemfile, Gemfile.lock, docs/_docs/install.md, docs/_reference/jets-new.md, jets.gemspec, lib/jets/commands/new.rb, lib/jets/commands/templates/skeleton/Gemfile.tt
* add --no-database option
* add install instructions about pg gem
addresses #33
=> remove pg dependency from jets and add as part of project Gemfile

lib/jets/router.rb
=> fix route resources macro for api mode

docs/_docs/action-filters.md, docs/_docs/deploy.md, docs/_docs/iam-policies.md, docs/_docs/minimal-deploy-iam.md, docs/_docs/polymorphic-support.md, docs/_includes/subnav.html, lib/jets/cfn/ship.rb, lib/jets/commands/deploy.rb
=> harden deploy on minimal stack rollback and add deploy iam policy docs

lib/jets/commands/new.rb, lib/jets/commands/sequence.rb, lib/jets/commands/templates/skeleton/.env.development.tt, lib/jets/commands/templates/skeleton/config/application.rb.tt, lib/jets/commands/templates/skeleton/config/database.yml.tt
Addresses #42 Application name should be inherited from folder name when dot is used
=> fix jets new .

docs/_docs/iam-policies.md, lib/jets/application.rb, lib/jets/aws_info.rb, lib/jets/commands/deploy.rb, lib/jets/core.rb, spec/lib/jets/application_spec.rb
=> fix application iam policy when Jets::Application.default_iam_policy used

lib/jets/application.rb, lib/jets/commands/build.rb, lib/jets/commands/sequence.rb, lib/jets/turbine.rb
Misc fixes:
* fix Jets Turbine require active support Fixes #78 
* fix jets new mode job copy_options
* fix has_poly? check to account for shared functions
* parse for project name as workaround to avoid double loading config/application.rb
=> misc fixes

lib/jets/builders/code_builder.rb
=> fix mega mode production deploy

lib/jets/cli.rb, lib/jets/commands/main.rb
=> support jets delete ENV

lib/jets/commands/import/sequence.rb
=> add import support for bitbucket and gitlab also

lib/jets/builders/gem_replacer.rb, lib/jets/builders/lambda_layer.rb, lib/jets/builders/rack_packager.rb, lib/jets/builders/ruby_packager.rb, lib/jets/builders/tidy.rb, lib/jets/commands/new.rb, spec/lib/jets/builders/tidy_spec.rb
* Attempt to fix weird #99 
* Also change `jets new --mode api demo` to use cli database option by default
=> bundle in vendor/gems to avoid vendor/bundle collison

lib/jets/camelizer.rb
=> Typo fix for PR101

lib/jets/application.rb, lib/jets/cfn/upload.rb, lib/jets/commands/templates/skeleton/config/application.rb.tt, lib/jets/overrides/rails/asset_tag_helper.rb
=> fix public assets folders to serve directly from s3

lib/jets/mega/request.rb
=> fix query string passed to mega request

lib/jets/builders/code_builder.rb, lib/jets/builders/ruby_packager.rb, lib/jets/turbo/rail.rb, lib/jets/util.rb
=> replace cp_r with rsync to handle special files like sockets

LICENSE.txt
Signed-off-by: Atul Bhosale <atul1bhosale@gmail.com>
- [] I've added tests (if it's a bug, feature or enhancement)
- [] I've adjusted the documentation (if it's a feature or enhancement)
- [] The test suite passes (run `bundle exec rspec` to verify this)
=> Update copyright notices to 2019 [ci skip]

.gitmodules, Gemfile.lock, jets.gemspec, lib/jets.rb, lib/jets/builders/tidy.rb, lib/jets/commands/db.rb, lib/jets/commands/db/tasks.rb, lib/jets/generator.rb, spec/lib/jets/application_spec.rb
=> remove Rails constant

lib/jets/turbo/project/Gemfile.lock
This is a 🐞 bug fix
- [] I've added tests (if it's a bug, feature or enhancement)
- [] I've adjusted the documentation (if it's a feature or enhancement)
=> update turbo Gemfile.lock

.github/PULL_REQUEST_TEMPLATE.md, lib/jets/resource/lambda/function/environment.rb
=> check reserved lambda variables and let user know

lib/jets/builders/code_builder.rb
=> special s3 url for us-east-1

CHANGELOG.md, lib/jets/commands/templates/skeleton/spec/controllers/posts_controller_spec.rb, lib/jets/commands/templates/skeleton/spec/spec_helper.rb.tt, lib/jets/core.rb, lib/jets/spec/helpers.rb, spec/lib/jets/spec/helpers.rb
Added long-awaited spec helpers :-)
=> Add jets/spec/helpers.rb

lib/jets/resource/api_gateway/cors.rb
https://community.rubyonjets.com/t/need-help-with-enabling-cors/71/7
=> fix cors headers

lib/jets/builders/ruby_packager.rb
=> improve remove bundled with in case it is not at the bottom in the future

docs/_reference/jets-new.md, lib/jets/commands/help/new.md, lib/jets/commands/sequence.rb
=> <!-- Thanks for creating a Pull Request! Before you submit, please make sure you've done the following:

lib/jets/dotenv.rb
https://community.rubyonjets.com/t/local-and-remote-environment/75/4
=> fix precedence of dotenv files

lib/jets/controller/rendering.rb
=> application/xml content-type on render xml

lib/jets/controller/rendering/rack_renderer.rb
https://community.rubyonjets.com/t/issue-with-cors-for-specific-domain/81
=> fix cors for specific domains

lib/jets.rb, lib/jets/util.rb
=> rsync detection, stop on sh fail

lib/jets/resource/api_gateway/domain_name.rb
=> strip trailing period from custom domain if set

README.md, docs/_docs/controllers.md, docs/_includes/commands.html, lib/jets/controller/rack/adapter.rb, spec/lib/jets/controller/base_spec.rb
Fix a typo across few documents: `compatiable` => `compatible`
=> Fix 'compatiable' typo in documentation

docs/faq.md
=> docs: How to added in FAQ for Lambdagems prompt

docs/_docs/cors-support.md, docs/_docs/database-support.md, docs/_docs/events-sns.md, docs/_docs/events-sqs.md, docs/_docs/events.md, docs/_docs/polymorphic-node.md, docs/_docs/tutorials.md, docs/_includes/cloudformation_links.md, docs/_includes/subnav.html, lib/jets/job/dsl.rb, lib/jets/job/dsl/event_source_mapping.rb, lib/jets/job/dsl/sns_event.rb, lib/jets/job/dsl/sqs_event.rb, lib/jets/lambda/dsl.rb, lib/jets/rack_server.rb, lib/jets/resource/sns.rb, lib/jets/resource/sns/subscription.rb, lib/jets/resource/sns/topic.rb, lib/jets/stack/main/extensions/sns.rb
This is a 🙋‍♂️ feature or enhancement. 
SNS Events Lambda Trigger Support
=> SNS Events Lambda Trigger Support

lib/jets/controller/middleware/local.rb, lib/jets/overrides/rails/common_methods.rb
Fixes on_aws detection when using cloud9 hostname.
Addresses #201
=> fix on_aws detection when using cloud9 hostname

lib/jets/aws_services.rb, lib/jets/aws_services/global_memoist.rb
Cache aws service clients globally for lambda performance.
=> cache aws service clients globally for lambda performance

lib/jets/commands/new.rb
Fixes issues from webpacker v3.5 to v4 upgrade
Fixes related to https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md
Also related to https://github.com/tongueroo/jets/issues/215
Original reported issue #215
=> Fix issues from webpacker v3.5 to v4 upgrade

lib/jets/aws_info.rb, lib/jets/camelizer.rb
=> Circle fix

lib/jets/commands/templates/skeleton/config/application.rb.tt
=> fix config.function.dead_letter_config in starter application.rb

lib/jets/generator.rb
=> little more cleanup

lib/jets/cfn/ship.rb
This is a 🐞 bug fix for issue #229
I would have liked to add a spec but since the spec for this class is currently completely stubbed out there wasn't an easy path for adding anything useful.
=> Fix ValidationError branch of Cfn::Ship#update_stack

lib/jets/controller/rack/adapter.rb, lib/jets/controller/rendering/rack_renderer.rb, lib/jets/processors/main_processor.rb
https://community.rubyonjets.com/t/possible-to-execute-jets-lambda-through-application-load-balancer/139/2
=> adjust resp when request coming from elb

docs/_docs/crud-html-activerecord.md, docs/_docs/crud-json-activerecord.md, docs/_reference/jets-new.md, lib/jets/commands/help/new.md, lib/jets/commands/sequence.rb
This is a 🐞 bug fix. (Kinda)
~- [ ] I've added tests (if it's a bug, feature or enhancement)~
~- [ ] I've adjusted the documentation (if it's a feature or enhancement)~
These are small copy changes for the CLI.
Definitely a patch level change, just copy changes.
=> Cli copy changes

lib/jets/commands/templates/skeleton/config/application.rb.tt, lib/jets/internal/app/functions/jets/base_path.rb
Custom domains are not working. Looks like the missing domain exception is now `Aws::APIGateway::Errors::InternalFailure` instead of `Aws::APIGateway::Errors::NotFoundException`. Will use a more generic exception class.
#255
=> Fix custom domain base mapping

lib/jets/middleware/default_stack.rb
Since stopped using shotgun for reloading in #254 , static files do not always get served in local development. This fixes that.
=> fix for static files now that not using shotgun

lib/jets/application.rb, lib/jets/controller/middleware/local/route_matcher.rb, lib/jets/router.rb
This fixes hot reloading from #254 It reloads routes for development on each request. 
#254
=> auto reload routes for development

lib/jets/controller/base.rb, lib/jets/controller/middleware/reloader.rb, lib/jets/middleware/default_stack.rb
* this serializes the requests
Fixes hot reloading during in development mode.
#280 #281 #282
=> use mutex during reloading

lib/jets/controller/middleware/reloader.rb
#282 #283
Use `@@reload_lock` instead of global variable to avoid possible collision.
=> use class @@reload_lock instead of global variable

lib/jets/stack.rb
Fixes shared resource eager loading so it doesn't error when there's an ActionMailer mailer.  Fixes #286
#286
=> fix shared eager loading

docs/_docs/env-files.md, lib/jets/booter.rb, lib/jets/dotenv.rb, lib/jets/dotenv/ssm.rb, spec/lib/jets/dotenv_spec.rb
* Refactoring dotenv/ssm into class
* Fix env ssm:relative_var by adjusting Jets boot order
* Improve error reporting of missing ssm names to user
#233
=> Dotenv ssm

lib/jets/application/defaults.rb, lib/jets/commands/templates/skeleton/config/application.rb.tt
Shorten the auto-generated vpc iam policy.
=> shorten auto iam policy for vpc

lib/jets/spec_helpers/request.rb
Rack utils already have methods for properly build a multipart body. Let's use it
Steps to reproduce:
it 'must create a message with valid params' do
valid_params = { name: "Cyril Ullrich", phone_number: "1-771-916-3775" }
post '/api/v1/feedbacks/messages', params: { message: valid_params }
end
In controller we get:
Parameters: {"message":"{:name=>\"Cyril Ullrich\", :phone_number=>\"1-771-916-3775\"}"}
Value is string
With fix:
Parameters: {"message":{"name":"Cyril Ullrich", "phone_number":"1-771-916-3775"}}
Value is hash
=> Use Rack::Multipart utils to properly build body params (especially with files and nested hashes)

lib/jets/mega/request.rb
Monitoring indicates that the rack subprocess can sometimes go away. It may be Lambda doing some maintenance and then it doesn't start back up the subprocess. Am guessing this because both the afterburner demo and mega mode demo lost the rack process near the same time. And they are 2 separate apps. 
Jets will automatically restart the rack process when this happens.
=> improve mega mode or afterburner, start back rack process if it dies

lib/jets/router/method_creator/code.rb
Just a small change that should result in the exact same outcome
N/A
Patch
=> Favor safe navigation operator in nil check

README.md
I noticed some opportunities to be nice to screen readers! 💻 
Relevant: https://blog.justinwflory.com/2019/06/markdown-accessible-images/
=> Add alt text to README screenshots

docs/_docs/extras/minimal-deploy-iam.md
Thanks so much for your work on this project!  As a "DevOps-ey" guy, the expansive permissions in this doc are going to be a sore spot with any security minded folks.  This smaller subset of privileges works for us.
=> Provide *minimal* privileges

docs/_docs/routing/guide.md, lib/jets/router/method_creator/code.rb, lib/jets/router/method_creator/edit.rb, lib/jets/router/method_creator/index.rb, lib/jets/router/method_creator/new.rb, lib/jets/router/method_creator/show.rb, lib/jets/router/route.rb, spec/lib/jets/router_spec.rb
* non-conventional routes dont auto-generate url helpers
* as: :disabled option
=> improvements to named route helpers

lib/jets/commands/dotenv.rb, lib/jets/dotenv/show.rb, lib/jets/dotenv/ssm.rb
Add `jets dotenv:show` convenience command
Patch
=> add jets dotenv:show command

lib/jets/booter.rb, lib/jets/stack/main/dsl.rb, lib/jets/stack/main/dsl/base.rb, lib/jets/stack/main/dsl/sqs.rb
* Fixes [Shared Resource Extensions](https://rubyonjets.com/docs/shared-resources/extensions/). 
* Introduces internal_finisher method
* Rename `getatt` to `get_att` and improve usability
Patch
=> introduce internal_finisher to fix shared resource extensions

docs/_docs/email/configuration.md
=> fix typo SMTP

docs/_docs/testing/controllers.md
=> Fix minor typo

docs/_docs/routing/authorizers/authorizer-tips.md
A small typo fix. "as" was said twice in a row. Changed to only once.
https://rubyonjets.com/docs/routing/authorizers/authorizer-tips/
=> Fix typo: "as as" --> "as"

lib/jets/job/base.rb, spec/lib/jets/job/base_spec.rb
=> fix on_lambda? check allow testing

LICENSE.txt
Changed copy write year from 2019 to 2021.
Changed copy write year from 2019 to 2021.
No.
It should not need any tests.
=> Update Copy Write Year

lib/jets/commands/templates/skeleton/Gemfile.tt
Update`pg` and `mysql2` gem to latest version in the generated Gemfile from running `jets new`
#554
Run
jets new demo
Patch
=> update pg version in jets new Gemfile to latest

lib/jets/cfn/upload.rb
Fix content-type s3 metadata when uploading assets like images.
#563
Deploy with a new svg image and confirm that it shows up in the deployed app.  Also, added an svg example in this [tongueroo/jets-webpacker-demo](https://github.com/tongueroo/jets-webpacker-demo)
**Some notes**
This fix only fixes new assets that will be uploaded. It does not fix assets already been uploaded. This is because jets optimizes the uploading process. Jets does an md5 checksum on the local assets and compares it with the asset on s3. When they match, Jets doesn't bother reuploading the asset. 
Added a `JETS_ASSET_UPLOAD_FORCE` env var to override this optimization:
JETS_ASSET_UPLOAD_FORCE=1 jets deploy
This will reupload **all** assets, which is fine, its just slower.
Additionally, browser …
=> fix content type s3 metadata

lib/jets/commands/dbconsole.rb
Fixes `rails dbconsole` command for activerecord 6.1+
Run `rails dbconsole`
Patch
=> fix dbconsole

lib/jets/controller/middleware/local/route_matcher.rb
Fix private method names. Now, `path` returns method and `method` returns path.
None
None
=> Fix private method names

lib/jets/commands/deploy.rb
see commentary in issue 592 for additional details.
Please note Issue #592 was created from my work account, though I made this PR from my personal account. 
This PR adds back in a rescue block into the `lib/jets/commands/deploy.rb#find_stack` method that was removed in a previous deploy and seems to have caused the issues I noted in issue #592.
I forked the project, added the rescue block into my fork and built and app using that fork and was able to successfully perform and initial deployment as well as an updated deployment on my personal machine (the second test machine I referenced in Issue #592.
Yes, this is connected to Issue #592. There is a lot of commentary in there. 
To Test:
1. Spin up demo Jets project with a single route and controller
2. Following the deploy instructions, …
=> Added rescue block back into lib/jets/commands/deploy.rb

lib/jets/booter.rb
I’ve recently had to connect to two databases, the first one to write data and the second to read it. 
I found in Jets, in booter.rb, a line that makes the connection with the database. Nowadays Jets use legacy connection and in this version I had to create an abstract class for each connection. I searched the internet and found the new version of Active Record that allows you to easily connect the model with the connection, using the "ActiveRecord::Base.connects_to" method.
I'm opening MR to allow Jets to use the new connection handling. 
Let me know your view over this change, and if you think it is a valid one, I’ll update the documentation.
In the project which use Jets, you will need to create one file into folder initializers with this content: …
=> Multiple Databases

lib/jets/resource/api_gateway/rest_api/logical_id/message.rb
Improve custom domain message when not fully setup
Sanity check of demo app suffices.
Patch
=> Custom domain messaging

lib/jets/cfn/builders/parent_builder.rb
AWS changed the default behavior of s3 buckets to block public access
* https://aws.amazon.com/blogs/aws/amazon-s3-block-public-access-another-layer-of-protection-for-your-accounts-and-buckets/
* https://github.com/aws-amplify/amplify-cli/issues/12503
Jets uploads assets to s3 bucket with acl: "public-read" here
* https://github.com/boltops-tools/jets/blob/c5858ec2706a606665a92c3ada3f16ae4c753372/lib/jets/cfn/upload.rb#L97
This update:
* Use minimal s3 bucket policy to allow public read access to assets.
* Add ObjectOwnership ObjectWriter rule to jets s3 managed bucket
Also, open to other ways to address this. Maybe a config option to enable this.
Note: This does not affect existing buckets. The OwnershipControls property is only added by AWS to newly created S3 …
=> fix assets upload during deploy

lib/jets/builders/code_builder.rb, lib/jets/cfn/upload.rb
Fix `Jets.logger` oppsie 🤦🏻‍♂️
Patch
=> fix Jets.logger call

lib/jets/controller/middleware/local/api_gateway.rb, lib/jets/controller/rack/env.rb, lib/jets/mega/hash_converter.rb, spec/fixtures/dumps/api_gateway/books/list.json, spec/fixtures/dumps/api_gateway/books/mounted_list.json, spec/lib/jets/controller/rack/env_spec.rb
Fix apigateway implementation that is different from the aws
aws event JOSN
=> [Fix] ApiGateway for local Middleware

lib/jets/commands/sequence.rb
- [X (no new new tests fail) ] The test suite passes (run `bundle exec rspec` to verify this) 
Fixes 
https://github.com/boltops-tools/jets/issues/525
Added the helpers dir to a fresh project using the `--mode jobs`  flag
Hop on my branch
gem build jets.gemspec
gem install --local jets-4.0.7.gem
Follow instructions in issue. 
patch
=> Fix broken --mode jobs new project generation 

CHANGELOG.md, jets.gemspec, lib/jets.rb, lib/jets/aws_services/stack_status.rb, lib/jets/builders/code_builder.rb, lib/jets/cfn/deployment.rb, lib/jets/cfn/resource/api_gateway/rest_api/logical_id.rb, lib/jets/cfn/resource/s3/jets_bucket.rb, lib/jets/command/api_helpers.rb, lib/jets/command/help/logs.md, lib/jets/command/help/releases.md, lib/jets/commands/delete/delete_command.rb, lib/jets/commands/releases/releases_command.rb, lib/jets/dotenv/ssm.rb, lib/jets/generators/overrides/app/templates/.jetsignore, lib/jets/job/dsl/dynamodb_event.rb
jets releases --sha option
jets-git info support
jetsignore public/files
Adds `jets release:info` command.
Patch
=> jets releases:info command

lib/jets/commands/releases/releases_command.rb
Improve `jets releases:info` output
Patch
=> improve releases:info output

lib/jets/cfn/builder/parent.rb, lib/jets/cfn/params/common.rb, lib/jets/core.rb
Make sure a brand new jets project with no code can deploy successfully.
#690 
jets new demo --mode api
cd demo
jets deploy
Patch
=> jets deploy fix for empty project

lib/jets/builders/code_builder.rb, lib/jets/cfn/builder.rb, lib/jets/cfn/builder/parent.rb, lib/jets/cfn/params/common.rb, lib/jets/cfn/ship.rb, lib/jets/core.rb, lib/jets/stack/builder.rb
Fix gem_layer? check
Make sure a brand new jets project with no code can deploy successfully.
Related
#690
#691
jets new demo --mode api
cd demo
jets deploy
Patch
=> fix jets deploy for empty project

lib/jets/spec_helpers/controllers.rb
Jets v5 controller testing is broken for get requests. If you attempt to pass params or a query, the params are not passed to the request correctly. Furthermore, adding a query i.e. `my/path?foo=bar` will not match with the route `my/path`.
This PR fixes the above bugs by extracting the query, merging it with any params passed in the options, removing the query from the path, and then passing these into the request correctly.
In your jets app, create a controller expecting a GET request with specific params which responds successfully only if specific params are present. Write a spec for this controller action, passing in params i.e.
`get '/my/path', params: { required_param: 'foo'}`
Prior to this PR, the params passed in will not be available to the controller …
=> Fix controller testing in jets 5 - handling of params and query

lib/jets/job/dsl/s3_event.rb, lib/jets/version.rb, spec/lib/jets/job/base_spec.rb
Allow custom SNS properties, such as filter policies, to be applied to s3_events.
```
class HardJob
S3_BUCKET = "test-bucket".freeze
SUBSCRIPTION_PROPS  = {
FilterPolicyScope: "MessageBody",
FilterPolicy: {
Records: {
s3: {
object: {
key: [
{ prefix: "test-prefix/" }
]
}
}
}
}.to_json
}.freeze
s3_event(S3_BUCKET, sns_subscription_properties: SUBSCRIPTION_PROPS)
def filtered
puts "Filtered event: #{JSON.dump(event)}"
end
s3_event(S3_BUCKET)
def unfiltered
puts "Unfiltered event: #{JSON.dump(event)}"
end
end
```
[https://github.com/rubyonjets/jets/issues/534](https://github.com/rubyonjets/jets/issues/534)
Test repo: https://github.com/SteffanPerry/s3-event-custom-properties
=> Support for s3 event sns configuration

.github/ISSUE_TEMPLATE/bug_report.md, Gemfile, Rakefile, lib/jets/cfn/resource/associated_outputs.rb, lib/jets/cli.rb, lib/jets/cli/ci/status.rb, lib/jets/cli/concurrency/get.rb, lib/jets/cli/concurrency/set.rb, lib/jets/cli/concurrency/unset.rb, lib/jets/cli/git.rb, lib/jets/cli/git/push.rb, lib/jets/cli/help/concurrency/info.md, lib/jets/cli/release/history.rb, lib/jets/cli/release/info.rb, lib/jets/core/config/project.rb, lib/jets/git/local.rb, lib/jets/lambda/definition.rb, lib/jets/lambda/dsl.rb, lib/jets/util/format_time.rb
* associated outputs concept, helps fix edge cases with sqs queue 
* jets concurrency show lambda function name
* jets git:push command
* pretty time helper
* update github issue template bug report
Sanity check and go through one of the learn guides, IE: https://docs.rubyonjets.com/docs/learn/rails/
Patch
=> small fixes

lib/jets/cfn/deploy.rb, lib/jets/cli/ci/logs.rb, lib/jets/cli/git/push.rb, lib/jets/core/config/project.rb
* Update `jets git:push` wrapper command. Note: This command may change. 
* Also alway log or show bootstrap sync errors when they occur
Patch
=> jets git:push

lib/jets/code/stager.rb
Use `du -ks` which works on both macosx and linux.
Deploy
Patch
=> fix du check for macosx
