lib/jets/server/timing_middleware.rb
Rack uses `X-Runtime` header to report request runtime. 
Also it uses `CLOCK_MONOTONIC` if available, to ensure that there no ntp-related artifacts in time measurements.
=> Replace `Timing` header with `X-Runtime`

lib/jets/aws_info.rb
=> Don't fail if AWS credentials are missing

lib/jets/aws_info.rb
Removes annoying `sh: 1: aws not found` message when aws cli is not available in PATH.
Before
```
$ bundle exec jets server
sh: 1: aws: not found
You can also get rid of this message by setting AWS_REGION or configuring ~/.aws/config with the region
=> bundle exec shotgun --port 8888 --host 127.0.0.1
Jets booting up in development mode!
Jets::Rack#start
== Shotgun/WEBrick on http://127.0.0.1:8888/
[2018-11-05 18:25:35] INFO  WEBrick 1.4.2
[2018-11-05 18:25:35] INFO  ruby 2.5.3 (2018-10-18) [x86_64-linux]
[2018-11-05 18:25:35] INFO  WEBrick::HTTPServer#start: pid=722 port=8888
```
After:
```
$ bundle exec jets server
=> bundle exec shotgun --port 8888 --host 127.0.0.1
Jets booting up in development mode!
Jets::Rack#start
== Shotgun/WEBrick on http://127.0.0.1:8888/
[2018-11-05 18:25:35] …
```
=> Fix notice when aws cli is not installed

lib/jets/aws_info.rb, lib/jets/commands/new.rb, lib/jets/commands/sequence.rb
This removes notice from git when name&email are not available in git config:
```
...
Done in 4.67s.
run  git init from "."
Initialized empty Git repository in /tmp/test-project/.git/
run  git add . from "."
run  git commit -m 'first commit' from "."
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'root@dcd54d225d69.(none)')
================================================================
Congrats 🎉 You have successfully created a Jets project.
Cd into the project directory:
cd test-project
To start a server and test locally:
jets server # localhost:8888 should have …
```
=> Fix notice when Jets fails to create first git commit

docs/_docs/routing.md, lib/jets/resource/api_gateway/cors.rb, lib/jets/resource/api_gateway/method.rb, lib/jets/route.rb, spec/lib/jets/resource/api_gateway/cors_spec.rb, spec/lib/jets/resource/api_gateway/method_spec.rb, spec/lib/jets/route_spec.rb
By default, each endpoint has an authorization type of NONE. This isn't very suitable for a lot of private APIs being built, so adding in the ability to customise. Updated documentation to show how to use it.
Testing:
- Added new spec tests, and ran existing ones. I noticed that some of the existing tests weren't running as part of a standard rspec call, and as a result an existing tests was broken (which I fixed).
- Ran "jets deploy" for a project containing routes both with and without authorization types and confirmed they were created correctly in AWS.
=> Add option to specify authorization type on a per-route basis.

docs/_docs/app-config.md, lib/jets/cfn/builders/api_gateway_builder.rb, lib/jets/commands/templates/skeleton/config/application.rb.tt, lib/jets/resource/api_gateway/rest_api.rb, spec/lib/jets/resource/api_gateway/rest_api_spec.rb
ApiGateway supports 3 different endpoint types (edge-optimised, private, and regional). I've kept the default as edge-optimised, but added the ability to configure the type via application configuration. The documentation for these variables seems to be in the example config, so I stuck with doing that.
Testing:
- Added new spec tests, and ran existing ones.
- Ran "jets deploy" for a project specifying an endpoint type and confirmed it was created correctly.
- Ran "jets deploy" for a project not specifying an endpoint type and confirmed it was created as 'EDGE', to preserve existing behaviour.
=> Add option to specify endpoint type of the ApiGateway.

docs/_docs/app-config.md, lib/jets/application.rb, lib/jets/cfn/builders/api_gateway_builder.rb, lib/jets/commands/templates/skeleton/config/application.rb.tt, lib/jets/resource/api_gateway/rest_api.rb, spec/lib/jets/resource/api_gateway/rest_api_spec.rb
related #75, adjust the option to `config.api.endpoint_type`:
Very through description from #75:
ApiGateway supports 3 different endpoint types (edge-optimised, private, and regional). I've kept the default as edge-optimised, but added the ability to configure the type via application configuration. The documentation for these variables seems to be in the example config, so I stuck with doing that.
Testing:
- Added new spec tests, and ran existing ones.
- Ran "jets deploy" for a project specifying an endpoint type and confirmed it was created correctly.
- Ran "jets deploy" for a project not specifying an endpoint type and confirmed it was created as 'EDGE', to preserve existing behaviour.
=> ApiGateway config.api.endpoint_type option

docs/_docs/routing.md, lib/jets/application.rb, lib/jets/resource/api_gateway/method.rb, lib/jets/resource/api_gateway/rest_api.rb
Related to #74. Also add `config.api.authorization_type` application-wide option in this PR.
Very through description from #74:
By default, each endpoint has an authorization type of NONE. This isn't very suitable for a lot of private APIs being built, so adding in the ability to customise. Updated documentation to show how to use it.
Testing:
- Added new spec tests, and ran existing ones. I noticed that some of the existing tests weren't running as part of a standard rspec call, and as a result an existing tests was broken (which I fixed).
- Ran "jets deploy" for a project containing routes both with and without authorization types and confirmed they were created correctly in AWS.
=> add config.api.authorization_type application-wide option

lib/jets/camelizer.rb
The SQS RedrivePolicy attributes aren't being camelized properly which results in an AWS API error...
`Value {"MaxReceiveCount":"4","DeadLetterTargetArn":"arn:aws:sqs:us-east-1:********:*************"} for parameter RedrivePolicy is invalid. Reason: Redrive policy does not contain mandatory attribute: maxReceiveCount. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: *******)`
=> Added SQS RedrivePolicy attributes to special map

lib/jets/lambda/dsl.rb
When creating custom resources, at times the resource id will be a symbol and it fails to create.
=> fix for undefined method `sub` for symbol

CHANGELOG.md, lib/jets/application.rb, lib/jets/commands/templates/skeleton/config/application.rb.tt, lib/jets/core.rb
This is a 🧐 documentation change (a little).
Add Jets.application.config.logger field to enable custom logger
instance to be configured in config/environments/*.rb files.
=> Add configurable Jets.application.config.logger

CHANGELOG.md, jets.gemspec
Fix jets.gemspec how git command is executed to list files. The listing no longer needs to be done from the jets root directory. This change enables including Jets as local bundler gem.
=> Fix jets.gemspec files listing method

CHANGELOG.md, lib/jets/controller/base.rb, lib/jets/controller/callbacks.rb, spec/lib/jets/controller/callbacks_spec.rb
Sorry, no documentation changes. Couldn't find Jets documentation about before_action.
When any before action renders or redirects, the filter chain
is halted, and the action code is not executed. This allows
before_action to act as guards like in Rails.
=> Change before_action behavior: allow chain break

CHANGELOG.md, lib/jets/controller/callbacks.rb, spec/lib/jets/controller/callbacks_spec.rb
Added these callbacks:
- prepend_before_action
- append_before_action (alias to before_action)
- prepend_after_action
- append_after_action (alias to after_action)
=> Add prepend/append_before/after_action callbacks

CHANGELOG.md, lib/jets/controller/callbacks.rb, spec/lib/jets/controller/callbacks_spec.rb
These could modify a global callback array if used first
=> Fix prepend_* callbacks: Global callback array fix

lib/jets/preheat.rb
Let me know if this is on the right track.
Prewarming Jobs seems of little value since they are intended to run in the background anyway. 
Related to #153
=> exclude Jobs from prewarm_all

lib/jets/resource/api_gateway/rest_api/routes/change/base.rb, lib/jets/resource/iam/application_role.rb, lib/jets/resource/iam/base_role_definition.rb, lib/jets/resource/iam/class_role.rb, lib/jets/resource/iam/function_role.rb, lib/jets/resource/lambda/function.rb, spec/lib/jets/resource/api_gateway/rest_api/routes/change/base_spec.rb, spec/lib/jets/resource/lambda/function_spec.rb
Remove pretty IAM role names. Do not assign pretty role_name because long controller names might hit the 64-char.  limit. Also, IAM roles are global, so assigning role names prevents cross region deploys.
#160
=> remove pretty iam role name, let CloudFormation generate name

lib/jets/application.rb, lib/jets/mega/request.rb
https://community.rubyonjets.com/t/error-errortype-function-encoding-undefinedconversionerror-on-marshall-response/68/5
=> use encoding from content-type for mega request

docs/_docs/routing-authorization.md, lib/jets/controller/base.rb, lib/jets/resource/api_gateway/method.rb, lib/jets/router.rb
Allows us to specify the authorization_type at the controller level. Example:
```ruby
class PostsController < ApplicationController
authorization_type :aws_iam
end
=> controller authorization_type declaration

CHANGELOG.md, lib/jets/resource/api_gateway/rest_api/routes/change/base.rb, lib/jets/resource/lambda/function.rb, spec/lib/jets/resource/api_gateway/rest_api/routes/change/base_spec.rb, spec/lib/jets/resource/lambda/function_spec.rb
Fixed two errors:
1. When route contains more than one variable in path, like:
`/posts/{id}/edit/{another_id}`
2. Invalid lambda function names for controllers in deep namespaces like:
`A::B::MyController`
=> Fix two routes errors (breaking paths and change detection)

CHANGELOG.md, lib/jets/spec_helpers.rb, lib/jets/spec_helpers/params.rb, lib/jets/spec_helpers/request.rb, spec/lib/jets/spec_helpers_spec.rb
Running `get "/path", query: { a: 1 }` now allows to execute an endpoint like `GET /path?a=1`.
=> spec_helpers: get request now accepts query params

lib/jets/booter.rb
* seems like on some systems Dir.glob returns paths in a different order
#193
=> fix jets eager load, order by path length

lib/jets/booter.rb
Changes `empty?` to `blank?` on the boot check for a configured database setup, to account for `nil`.
Fixes tongueroo/jets#203
1.8.7
=> Fix for error message on booting with missing database environment

lib/jets/stack/main/extensions/lambda.rb
Fix bug that prevents s3 event from working with really long bucket names.
=> fix s3 event function for long bucket names

.gitignore, docs/_docs/action-filters.md, docs/_docs/minimal-deploy-iam.md, docs/_docs/rescue-from.md, docs/_includes/subnav.html, lib/jets/controller.rb, lib/jets/controller/base.rb, lib/jets/controller/callbacks.rb, spec/lib/jets/controller/base_spec.rb, spec/lib/jets/controller/rescuable_spec.rb
Provides functionality to allow Jets controllers to rescue from defined errors with specified error handlers, similar to Rails `rescue_from`.
Provides functionality requested in #207.
I would recommend release in a new `MINOR` release.
=> Use ActiveSupport::Rescuable in base Jets controller

docs/_docs/contributing.md
Add info about git submodules on contributing documentation.
=> Add git submodules to contributing documentation.

lib/jets/generator.rb
I've not added tests as the tests around generators are quite bare, likely because it relies a lot on Rails generators. I would be happy to help write tests for the generators as part of a bigger piece of work on this.
When generating a controller for an API mode application, Jets currently generates helpers and views. Rails wouldn't generate those in API mode.
This fixes the generator config for API mode.
=> Better API mode controller generator

docs/_docs/considerations-api-gateway.md
The link "Routing Overview" on [API Gateway Routes
](http://rubyonjets.com/docs/considerations-api-gateway/) was broken. I fixed it. 
PR for https://github.com/tongueroo/jets/issues/236
=> Fix routing link in considerations-api-gateway doc

lib/jets/application.rb, lib/jets/booter.rb
Fixes autoloading when there are concerns folders.
> RE: I have imported app/models from an app to our serverless jets application using git submodule. Now my jets command won't work because it has dependency on files inside app/models/concerns directory. I tried adding this code config.extra_autoload_paths = ["#{Jets.root}/app/models/concerns"] in application.rb, but it won't work. Could you guide me?
Think what is happening is that with way concerns are organized it messes up the Jets eager loading. Jets loads your app classes as part of bootup. This adds folders like `app/models/concerns` and `app/controllers/concerns` to the autoload paths and also allows them to work.
=> autoload concerns and allow them to work

spec/spec_helper.rb
…arf otherwise
This is a minor change to use an absolute path for `ENV['HOME']` when running tests. Ruby 2.5.3 throws an exception on some of the File/Path I/O operations if the home directory is a relative path. It caused several specs to fail. 
This change only affects development, so it doesn't need to be released with any particular version.
=> Set ENV['HOME'] to an absolute path

lib/jets/rack_server.rb
The AWS Ruby Runtime changed so that a TCPSocket.new now throws a `Errno::EAFNOSUPPORT` error when the rack server for afterburner mode is not yet up.  This rescues from that exception also.
=> fix wait_for_socket on aws lambda, rescue Errno::EAFNOSUPPORT

lib/jets/overrides/rails/common_methods.rb
Fixes bug when the /dev is added to urls to view helpers when hitting the cloud9 url. This is reproducible when running:
jets server --port 8080 
And hitting the jets app with the cloud9 url and viewing the HTML source.
**Good**:
**Bad**:
https://community.rubyonjets.com/t/local-jets-server-causes-404-in-cloud9-because-of-dev-path-prefix/150/10
=> dont add /dev prefix if on_cloud9

docs/_docs/shared-resources/functions.md, docs/_reference/jets-server.md, jets.gemspec, lib/jets.rb, lib/jets/application.rb, lib/jets/commands/main.rb, lib/jets/controller/base.rb, lib/jets/core.rb, lib/jets/lambda/dsl.rb, lib/jets/stack.rb, lib/jets/stack/main/dsl.rb
* use zeitwerk as autoloader
* remove jets server `--reload` option
* adjust default autoload path
* fix shared functions docs
Change the autoloader to use zeitwerk instead of ActiveSupport. This allows us to use hot-reloading for development and web requests pretty easily.
Related issues: #253 #240
=> speed up hot reloading in development

lib/jets/commands/build.rb
Jets deploy fails when there's a concerns module in the controllers folder. This fixes it by not generating unnecessary shim handlers for concerns.
https://community.rubyonjets.com/t/unable-to-autoload-constant-concerns-exceptionhandler/167
=> dont generate handlers for concerns

lib/jets/controller.rb, lib/jets/controller/rendering.rb, lib/jets/controller/stage.rb, lib/jets/overrides/rails/common_methods.rb
In local development mode, when updating a record, Jets controllers redirect to a url that includes the `/dev` when using the cloud9 development endpoint.
https://community.rubyonjets.com/t/local-jets-server-causes-404-in-cloud9-because-of-dev-path-prefix/150/11
=> fix stage name in dev mode for redirect also

lib/jets/mega/request.rb, spec/lib/jets/mega/request_spec.rb
Mega request proxy is able to handle responses with `body: nil`. For example 304 Not Modified responses.
=> Handle nil body on mega request proxy

lib/jets/application.rb, lib/jets/controller/middleware/local/route_matcher.rb
fixes bug so jets url shows up after jets deploy
After a `jets deploy` it does not show the API Gateway endpoint url, this fixes it so it shows back up.
Regression fix for #264
=> only refresh routes on dev middleware request

lib/jets/booter.rb, lib/jets/commands/base.rb, lib/jets/commands/build.rb, lib/jets/commands/dynamodb/migrator.rb, lib/jets/controller/rendering/rack_renderer.rb, lib/jets/klass.rb, lib/jets/lambda/dsl.rb, lib/jets/lambda/function_constructor.rb, lib/jets/poly_fun.rb, lib/jets/preheat.rb, lib/jets/processors/deducer.rb, lib/jets/resource/api_gateway/method.rb, lib/jets/resource/child_stack/app_class.rb, lib/jets/resource/child_stack/shared.rb, lib/jets/stack.rb, lib/jets/stack/depends.rb, lib/jets/stack/main/dsl.rb, lib/jets/stack/output/lookup.rb, lib/jets/stack/parameter/dsl.rb
Been mistakenly using classify instead of camelize to convert words to their class names. This fixes that. Normally, if your class names were plural, then this might break your app.  However, because Jets does an eager load of the app as a sanity check before deploying, in theory should not break your app since it prevent your app from deploying anyway. See #227 
Will be bumping a minor version for this.
Related to #227
minor
=> Replace classify with camelize

lib/jets/commands/templates/webpacker/app/javascript/src/jets/crud.js
Looks like core-js module removed Array.find. This breaks the starter crud.js as babel is not able to compile it. Using $ instead.
* use $ finder instead of .find
<details>
<summary>Error when running bin/webpack</summary>
$ JETS_ENV=development bin/webpack                          
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you …
=> Fix starter crud.js due to core-js module

lib/jets/application.rb
Fixes `jets deploy` for job mode when there's no `config/routes.rb` file.
Bug report #270
=> fix deploy for job mode with no config/routes.rb file

.gitmodules, jets.gemspec, lib/jets.rb
Removes the vendor/jets-gem. Using gem now.
=> remove jets-gems as vendor dependency

lib/jets/bundle.rb
On some systems, there's a ruby and bundler issue where `require "bundler/setup"` throws an error.  Think this may be because `bundler.rb` exists at 2 places. Found them here on my system:
$ find /home/ec2-user/.rbenv/versions/2.5.3/ -name bundler.rb
/home/ec2-user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler.rb
/home/ec2-user/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler.rb
$ 
When the `site_ruby/2.5.0/bundler.rb` is older or does not have `bundler/setup.rb` it will cause an LoadError.  This was reported in the community forums.  Removing `site_ruby/2.5.0/bundler/setup.rb` mimics the error:
$ jets server
Traceback (most recent call last):
13: from /home/ec2-user/.rbenv/versions/2.5.3/bin/jets:23:in `<main>'
12: from …
=> warn about bundler/setup failure

lib/jets/cfn/ship.rb
When deploying jets is failed by cloud formation issue, the console shows [a debugging cloud formation docs url](https://rubyonjets.com/docs/debugging-cloudformation/). But this url is not found 404. So I change it into [worked url](https://rubyonjets.com/docs/debugging/cloudformation/).
* [Current not worked Debugging CloudFormation Jets Docs Link](https://rubyonjets.com/docs/debugging-cloudformation/)
* [Worked Debugging CloudFormation Jets Docs Link](https://rubyonjets.com/docs/debugging/cloudformation/)
This is so minor changes.
=> Correct debugging cloud formation url

lib/jets/controller/rendering/rack_renderer.rb
Since #254 speed up hot reloading in development, views are not reloading in development mode. This fixes it.
=> hot reload views for development mode

lib/jets/middleware/default_stack.rb
Optimize development middleware by moving the reloader middleware after the shotgun static middleware. This allows the static middleware to serve static assets without hitting the `@@reload_lock` mutex. So static assets can be served in parallel locally. For apps with a lot of static assets, this is a good win.
#283 #284
=> optimize by moving reloader middleware after the shotgun static 

lib/jets/commands/call.rb
Fix the generated link to the AWS lambda config
=> Fix lambda url

docs/_docs/events/sns.md, docs/_docs/events/sqs.md, lib/jets/resource/child_stack/shared.rb, lib/jets/stack/main/dsl/sqs.rb
Add sqs url to shared sqs queue resource output. This allows us to grab the sqs url programatically. Example: `List.lookup(:waitlist_url)`.
app/shared/resources/list.rb:
```ruby
class List < Jets::Stack
sqs_queue(:waitlist)
end
```
app/jobs/hard_job.rb:
```ruby
class HardJob < ApplicationJob
class_timeout 30 # must be less than or equal to the SQS queue default timeout
depends_on :list # so we can reference list shared resources
sqs_event ref(:waitlist) # reference sqs queue in shared resource
def fix
puts "fix #{JSON.dump(event)}"
puts "sqs arn: #{List.lookup(:waitlist)}"
puts "sqs url: #{List.lookup(:waitlist_url)}"
end
end
```
Also:
* fix bug with camelize of the shared resource class name, not using using singularize
* also …
=> add sqs url to shared sqs queue resource

docs/_docs/iam-policies.md, lib/jets/application.rb, lib/jets/internal/app/jobs/jets/preheat_job.rb
Brought up in Jets community: [WarmLambdaFunction, TorchLambdaFunction dose not use my configured role](https://community.rubyonjets.com/t/warmlambdafunction-torchlambdafunction-dose-not-use-my-configured-role/188) 
This allows users to adjust the generated IAM policy associated with the [Jets::PreheatJob](https://github.com/tongueroo/jets/blob/master/lib/jets/internal/app/jobs/jets/preheat_job.rb) that handles [Prewarming](https://rubyonjets.com/docs/prewarming/)
https://community.rubyonjets.com/t/warmlambdafunction-torchlambdafunction-dose-not-use-my-configured-role/188
=> allow adjustment for preheat job iam policy

lib/jets/resource/api_gateway/rest_api/routes/change/base.rb
The lambda client helper that [Jets::AwsServices](https://github.com/tongueroo/jets/blob/master/lib/jets/aws_services.rb) provides is not named aws_lambda because of #232 We missed a rename. This bug shows up when routes have changed. This fixes it.
* Related to #232
* Reported: https://community.rubyonjets.com/t/something-special-about-environment-named-dev/194
=> fix routes change detection, aws_lambda client

docs/_docs/env-files.md, jets.gemspec, lib/jets/dotenv.rb, spec/lib/jets/dotenv_spec.rb
Mimics the same behaviour and interpolation syntax found in `serverless`, ie: `${smm:<parameter-name>}` (https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-using-the-ssm-parameter-store). However it will default to decrypting secure parameters and does not attempt to add any weird syntax for toggling the functionality. It seems to me that 99.9% of cases will want decrypted values. If anyone has any real world use cases for wanting encrypted values instead we could expand on the syntax with a disabling feature later.
We also introduce conventions for relative vs absolute paths. For example:
`${ssm:relative-variable}` will be expanded to `${ssm:/<app-name>/<jets-environment>/relative-variable}` while an absolute …
=> Interpolate values from SSM Parameter Store when initializing Dotenv

docs/_docs/env-files.md, lib/jets/dotenv.rb
Added support so that `.env.development.2` when `JETS_ENV_EXTRA=2` is set is loaded. 
In working on this, discovered the dotenv precedence was incorrect again? A little confused by this as though I had fixed this. Here are some related links to show the history:
* #171 fix precedence of dotenv files - from https://community.rubyonjets.com/t/local-and-remote-environment/75/4
* #214 Update dotenv.rb - had closed this PR because when I tested it, at the time, the precedence order was right
* There's a report on the dotenv project also that may be related: https://github.com/bkeepers/dotenv/issues/392
When when I tested today, the precedence was incorrect again... Thought it might change in one of …
=> dotenv env extra support, fix precedence again

lib/jets/aws_info.rb, lib/jets/dotenv.rb, lib/jets/resource/lambda/function/environment.rb
The Jets boot process calls the sts get-caller-identity api to get info about region and account id. This network call can sometimes error. So removing the need to make network calls from the bootup process.
Also, removes ssm calls from Jets bootup process. So kills 2 birds with one stone here.
* https://community.rubyonjets.com/t/jets-once-sometime-stuck-with-init-seahorse-networkingerror-error-on-aws-lambda/201
* #297
=> No network boot

docs/_docs/rails-support.md, lib/jets/turbo/rails.rb
Use the `.jets/project` instead of `.jets/app` folder for afterburner wrapper jets app. This avoids confusion when adding app files. IE:
* .jets/app/app/jobs/hard_job.rb # confusing double app/app
* .jets/project/app/jobs/hard_job.rb # better project/app
https://community.rubyonjets.com/t/how-to-test-an-afterburner-job-from-lambda-test-events/203/3
=> Dot jets project

lib/jets/commands/call/autoload_guesser.rb
Improve the `jets call` guesser. At the very start, assume that the right underscored and dashed function name is passed and look up class based on that. 
This fixes prewarming issues.  
Note, could had also pass the `guess: false` option also the the `Jets::Call` class but the guesser logic has some nice logic that handles longer function names #301 Instead just going to make the guesser better. 
https://community.rubyonjets.com/t/prewarm-function-guesses-errors/206/5
=> improve jets call guesser, do a simple detection at the start

CHANGELOG.md, lib/jets/controller/callbacks.rb, lib/jets/resource.rb, lib/jets/resource/api_gateway/method.rb, lib/jets/resource/api_gateway/resource.rb, spec/lib/jets/controller/callbacks_spec.rb, spec/lib/jets/resource/api_gateway/method_spec.rb
This patch limits the API Gateway resource names to 62 characters. Sorry for pushing it so late. Have been delegated to a different project...
I've seen this pull request: #301 it seems it does something similar for Lambda, not API Gateway. Am I right?
Let me know if you want me to refactor it somehow.
=> API Gateway: Limit resource names to 62 (!) characters

lib/jets/resource/api_gateway/resource.rb, spec/lib/jets/resource/api_gateway/resource_spec.rb
Fix this route:
config/routes.rb:
```ruby
Jets.application.routes.draw do
get "url-with-dash", to: "posts#index"
end
```
https://community.rubyonjets.com/t/deployment-failing-when-there-is-a-dash-in-a-route-name/211/2
=> allow url paths that contain dashes

lib/jets/commands/templates/skeleton/Gemfile.tt
The config/database.yml file needs to get removed, otherwise
the Jets boot process will try to setup the database which
will crash because of missing gem.
=> Update comment in Gemfile template

lib/jets/builders/code_builder.rb
I did not find any tests related to the `CodeBuilder` class, however, happy to implement if you can point me to it.
Copy .ruby-version file to build directory to make sure to use the same ruby version as in the project.
Fix #313
See #313 for details. We need to use the same ruby version in build directory `/tmp` as in the project directory.
None
=> Copy .ruby-version file to build directory

lib/jets/builders/code_builder.rb
Fix `jets deploy` when `/tmp/jets/PROJECT` does not yet exist on the first deploy.
Related: #316
=> fix jets deploy when no /tmp/jets exists yet

docs/_reference/jets-degenerate.md, docs/_reference/jets-generate.md, lib/jets/cli.rb, lib/jets/commands/main.rb, lib/jets/generator.rb
* also improve `jets generate scaffold` help menu to not require `-h` flag
Rails const was accidentally reintroduced in v2. This removes it again. 
https://community.rubyonjets.com/t/why-does-jets-define-rails-module/29/6
=> fix remove Rails const

lib/jets/spec_helpers/controllers.rb
Adds routes helpers for the spec helpers for controllers.  
* #308 Mentioned here
* https://community.rubyonjets.com/t/advanced-routes/77/9
=> spec helpers: include routes helper

lib/jets/controller/base.rb
In rails controller, the `action_name` method gives you access of current action being called. 
This is needed when using other gems that rely on this information. I've added to my base controller and it is working but adding it here will give us all the benefit.
Currently the router uses `controller.action_name` and passes that to base controller as `meth`. 
x.x.+
=> Controller action_name method

lib/jets/util.rb
This is a small change to properly escape paths passed directly to rsync on the command line in case the path contains special characters. 
The volume on my MacBook Pro has a space in the name, which broke jets when trying to run `jets deploy`. This fixed the issue. Shellwords is available on all Rubies since, I believe, 1.9.x. 
NOTE: I didn't add a test, I'm not sure how to effectively test for this, or if it is worthwhile. I'd appreciate guidance on the tests you'd like, if any. 
Recommended for a
=> Escape paths passed to rsync

lib/jets/builders/tidy.rb
It is quite common in Ruby to add `vendor` directory to `.gitignore` to not add dependencies to version control. However, Jets aggressively removes everything from `.gitignore`. I think we should keep the `vendor` directory as there is a dedicated step `clean_vendor_gems` already.
If `vendor` is in `.gitignore` file, the deployment will fail because `rsync` of the gem directory will fail.
=> Always keep vendor directory

spec/lib/jets/builders/tidy_spec.rb
The test broke with aae2d16b3801d83d78675ad526da2448a409667c
=> Fix tidy_spec

lib/jets/cfn/ship.rb
Because it is not a success so we shouldn't return exit status 0. This is especially important for CI to stop additional steps (e.g. deploy production after deploying staging)
=> Return exist status 1 if deployment fails

lib/jets/application/defaults.rb, lib/jets/controller/base.rb, lib/jets/resource/api_gateway/method.rb, lib/jets/router/route.rb, spec/lib/jets/resource/api_gateway/method_spec.rb
- [x ] I've added tests (if it's a bug, feature or enhancement)
- [x ] The test suite passes (run `bundle exec rspec` to verify this)
AWS API Gateway has build-in support for API Keys. More info here
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-usage-plans.html
This pull request allows configuring API methods to enable this feature.
You can configure the feature at different levels:
Application level:
```
Jets.application.configure do
config.api.api_key_required = true
end
``` 
Controller level:
```
class PostsController < ApplicationController
api_key_required true
end
``` 
Route level:
```
Jets.application.routes.draw do
get  "posts", to: "posts#index", api_key_required: true
end
``` …
=> Support for "apiKeyRequired" option for API method #334

docs/_docs/extras/action-filters.md, lib/jets/controller/callbacks.rb, spec/lib/jets/controller/callbacks_spec.rb
This is a 🙋‍♂️ feature or enhancement. 
Adding capability to define `only` option in the skip_before_action method; by adding the method(s) in the `only` list to the action's except list.
Have global actions defined in the controller's base, but allow the children controllers to be able to skip that action to certain methods only;
example above has the ApplicationController with a before_action that ensures the user to be logged in. 
and the PostController that also extends the action; but allows only one of its method to skip the `authenticate_user`. other methods in the PostController are still being protected by `authenticate_user`
```ruby
class ApplicationController < Jets::Controller::Base
before_action :authenticate_user
class PostController < ApplicationController …
```
=> Skip before action options

docs/_docs/app-config.md, lib/jets/application/defaults.rb, lib/jets/resource/api_gateway/rest_api.rb, spec/lib/jets/resource/api_gateway/rest_api_spec.rb
Deploying with `config.api.endpoint_type = 'PRIVATE'` fails in CloudFormation because Private REST API doesn't have a resource policy attached to it.
> Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: **********)
This PR implements an `config.api.endpoint_policy` configuration.
See https://community.rubyonjets.com/t/how-do-i-apply-a-resource-policy-to-a-private-api-gateway-deploy/241/2
=> Implement endpoint_policy configuration

lib/jets/spec_helpers/controllers.rb
Bug: Request headers are cached between specs. 
https://community.rubyonjets.com/t/is-jets-spechelpers-controllers-request-being-cached/244/2## Version Changes
=> spec helpers: dont cache requeset headers between specs

lib/jets/controller/base.rb, lib/jets/router/helpers/core_helper.rb
Adds the `helper_method` macro controllers. Allows you to take methods from controllers and make them available as helpers in views.
=> controller helper_method

docs/_docs/crud-html-activerecord.md, docs/_docs/crud-json-activerecord.md, jets.gemspec, lib/jets/application.rb, lib/jets/booter.rb, lib/jets/commands/db/tasks.rb, lib/jets/commands/db/tasks/dummy/app.rb, lib/jets/commands/db/tasks/dummy/config.rb, lib/jets/commands/import/templates/config/database.yml, lib/jets/commands/templates/skeleton/config/database.yml.tt, lib/jets/turbo/templates/config/database.yml, spec/fixtures/apps/franky/config/database.yml, spec/fixtures/db_configs/database.multi.yml, spec/fixtures/db_configs/database.single.yml, spec/lib/jets/application_spec.rb
Rails 6 has been released. This upgrades jets to use Rails 6 components instead of Rails 5.
=> upgrade to use rails 6 components

docs/_docs/prewarming.md
I was always wondering why Jets actually creates two additional functions, `warm` and `torch` (I found the naming not very intuitive). As I found out, the difference is that `torch` is using concurrency.
Additionally I fixed a typo in the example (please double check or elaborate why this is correct).
Last but not least, I don't really understand why concurrency is necessary and which number of concurrency I should choose for my Lambda function. My understanding so far, if I want my Lambda function to handle e.g. `20` requests concurrently, I should use concurrent `20`. The concurrent option will make sure that the function is not only prewarmed but also scaled for the amount of concurrency I expect. @tongueroo if you could confirm this and/or elaborate …
=> Update prewarming docs

lib/jets/controller/middleware/local/route_matcher.rb, lib/jets/router/finder.rb, lib/jets/router/matcher.rb, lib/jets/spec_helpers/controllers/request.rb, spec/lib/jets/controller/middleware/local/route_matcher_spec.rb, spec/lib/jets/router/matcher_spec.rb, spec/lib/jets/spec_helpers_spec.rb
Currently, using named routes or having route parameters in specs did not work. For instance:
```ruby
get '/spec_helper_test/123' # route not found
get helper_path(123) # route not found
get '/spec_helper_test/:id', id: 123 # works
```
The latter syntax is quite awkward and not intuitive.
This commit extracts the route matcher and finder in dedicated classes to reuse them in the middleware as well as in the spec helper.
The actual change is quite small, however, the diff is big because extracting the code from the middleware to the `Matcher` and `Finder` classes.
Let me know if I should do any adaptions or if you have some feedback. Thanks!
=> Fix route params for specs

docs/_docs/app-config.md, docs/_docs/extras/upgrading.md, lib/jets/application.rb, lib/jets/application/defaults.rb, lib/jets/autoloaders.rb, lib/jets/booter.rb, lib/jets/cli.rb, lib/jets/commands/base.rb, lib/jets/commands/templates/skeleton/config/application.rb.tt, lib/jets/commands/upgrade.rb, lib/jets/lambda/dsl.rb, spec/fixtures/apps/franky/config/application.rb
🙋‍♂️ feature or enhancement.
Fix `config.autoload_paths`. Also renamed it from `config.extra_autoload_paths` to `config.autoload_paths`. The [jets upgrade](https://rubyonjets.com/docs/extras/upgrading/) command will handle this.
https://community.rubyonjets.com/t/config-extra-autoload-paths-doesnt-seem-to-work/224/3
=> Fix autoload config

docs/_docs/jets-turbines.md
Clarify the difference between a Turbine and initializer. Following up on this discussion
https://community.rubyonjets.com/t/what-is-the-purpose-of-the-initializer-turbines/251/4
=> Update Turbine documentation

lib/jets/commands/deploy.rb, lib/jets/commands/main.rb, lib/jets/router.rb
Check that the routes are valid on the `jets routes` command also. Prints out a warning if there are missing controllers.
https://community.rubyonjets.com/t/how-significant-is-jets-2-x/253/9
=> improve jets routes command to also validate routes

.gitignore, lib/jets/cfn/builders/api_gateway_builder.rb, lib/jets/cfn/builders/api_resources_builder.rb, lib/jets/cfn/builders/parent_builder.rb, lib/jets/cfn/built_template.rb, lib/jets/naming.rb, lib/jets/resource/api_gateway/resource.rb, lib/jets/resource/api_gateway/rest_api/change_detection.rb, lib/jets/resource/api_gateway/rest_api/routes/change.rb, lib/jets/resource/api_gateway/rest_api/routes/change/base.rb, lib/jets/resource/api_gateway/rest_api/routes/change/media_types.rb, lib/jets/resource/api_gateway/rest_api/routes/change/page.rb, lib/jets/resource/api_gateway/rest_api/routes/change/to.rb, lib/jets/resource/api_gateway/rest_api/routes/change/variable.rb, lib/jets/resource/child_stack/api_resource.rb, lib/jets/resource/child_stack/api_resource/page.rb, lib/jets/resource/child_stack/app_class.rb, spec/fixtures/resource_pages/demo-test-api-resources-1.yml, spec/fixtures/resource_pages/demo-test-api-resources-2.yml, spec/fixtures/resource_pages/demo-test-api-resources-3.yml, spec/lib/jets/cfn/builders/api_gateway_builder_spec.rb, spec/lib/jets/cfn/builders/api_resources_builder_spec.rb, spec/lib/jets/resource/api_gateway/resource_spec.rb, spec/lib/jets/resource/api_gateway/rest_api/routes/change/page_spec.rb, spec/spec_helper.rb
This allows apps to have more than 60 routes if needed.
* Also, update route change detection to account for pagination.
https://community.rubyonjets.com/t/cloudformation-outputs-limits-60/246/3
=> paginate api gateway resources to support more routes

lib/jets/aws_services/stack_status.rb, lib/jets/commands/clean/log.rb, lib/jets/commands/delete.rb, lib/jets/commands/deploy.rb, lib/jets/resource/api_gateway/rest_api/routes/change/base.rb
With larger apps, deploys can fail from [AWS rate limiting](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html). This adds some logic to handle it.
=> rate limit backoff

lib/jets/controller/redirection.rb
Add `redirect_back` controller method.
https://github.com/tongueroo/jets/issues/352
=> redirect_back method

docs/_docs/extras/deploy-stagger.md, docs/_includes/subnav.html, lib/jets/application/defaults.rb, lib/jets/aws_info.rb, lib/jets/cfn/builders/base_child_builder.rb, lib/jets/cfn/builders/parent_builder.rb, lib/jets/cfn/builders/parent_builder/stagger.rb, lib/jets/lambda/functions.rb, lib/jets/resource/child_stack/app_class.rb, lib/jets/stack/depends.rb, lib/jets/stack/depends/item.rb, spec/lib/jets/cfn/builders/parent_builder/stagger_spec.rb
* add stagger to slow down deploy if needed
* docs: config.deploy.stagger options
* specs: stagger_spec.rb
Users with rather larger Jets applications (hundreds of lambda functions) are running into internal AWS Lambda -> EC2 Rate limits.   This adds stagger options which slow down the deploy to mitigate running up against the rate limit.  Example:
config/application.rb:
```ruby
config.deploy.stagger.enabled = true  # default is false
config.deploy.stagger.batch_size = 10 # default is 10
```
Interestingly, tested with a Jets application with more than 200 Lambda functions and was unable to trigger the internal Lambda rate limit. 
Others have reported running into this though 🧐 …
=> stagger deploy option

lib/jets/builders/code_builder.rb
Fixes edge case for Jets Afterburner deploy mode. If the rails project has a `.ruby-version` then the deploy fails. This fixes it.
Report: #363
Related: #317 #316 #313
=> fix copy ruby version

docs/_docs/crud-html-activerecord.md, docs/_docs/crud-json-activerecord.md, lib/jets/commands/import/templates/config/database.yml, lib/jets/commands/templates/skeleton/config/database.yml.tt
This pull changes the encoding for postgres database configurations. By default the utf8mb4 encoding would be used for both mysql and postgres. This is incorrect as postgres returned an error upon trying to use utf8mb4 as encoding.
Rails itself also using the unicode encoding for postgres, see: https://github.com/rails/rails/blob/235eb91bad58ab18b45aa36fa3a1ebedfe1c4879/railties/lib/rails/generators/rails/app/templates/config/databases/postgresql.yml.tt.
I couldn't find where the `jets new` command is being tested so not sure if tests should still be added for this. If so I could use some guidance on that.
This is not related to any other issue. Upon creating a new jets project using postgres I received the following error:
`PG::Error: ERROR:  invalid value for …
=> Use unicode for encoding when using postgres.

lib/jets/authorizer/dsl.rb
Fix a bug when only cognito authorizers are being used w/o any lambda authorizers.
https://community.rubyonjets.com/t/deploying-is-failing-with-cognito-authorizer/266
Patch
=> fix to allow using only cognito authorizers

lib/jets/spec_helpers.rb
fix rspec execution for projects with no database
Fixes #373 
Related #346
Patch
=> fix rspec execution for projects with no database

lib/jets/aws_info.rb, lib/jets/aws_services/stack_status.rb, lib/jets/builders/code_size.rb, lib/jets/cfn/status.rb, lib/jets/commands/dynamodb/migrator.rb, lib/jets/commands/templates/skeleton/spec/spec_helper.rb.tt, lib/jets/controller/forgery_protection.rb, lib/jets/controller/middleware/local.rb, lib/jets/erb.rb, lib/jets/internal/app/jobs/jets/preheat_job.rb, lib/jets/preheat.rb, lib/jets/processors/main_processor.rb, spec/fixtures/apps/franky/app/jobs/easy_job.rb, spec/fixtures/apps/franky/spec/spec_helper.rb, spec/spec_helper.rb
* use `JETS_TEST=1` env var instead of `TEST=1` for specs
* favor Jets.env.test? method in code
=> use JETS_TEST env var instead and favor Jets.env.test? method

lib/jets/cfn/builders/controller_builder.rb
Allow creation of [Assocaited Resources](https://rubyonjets.com/docs/function-resources/) within controllers.
Gitter question
patch
=> associated resources support for controllers

lib/jets/cfn/builders/interface.rb, lib/jets/cfn/builders/parent_builder.rb, lib/jets/cfn/builders/util/source.rb
Adds Jets version and Code version (git sha) to parent stack description. 
Only supports git right now. It's a start.
Patch
=> add jets and code version to parent template description

lib/jets/cfn/ship.rb, lib/jets/cfn/template.rb, lib/jets/cfn/template_source.rb, spec/lib/jets/cfn/template_source_spec.rb
Upload CloudFormation template to s3 bucket if a bucket present
Fix issue https://github.com/tongueroo/jets/issues/379
I think PATCH version can be applied
=> Fix issue templateBody failed to satisfy constraint: Member must have length less than or equal to 51200

lib/jets/tmp_loader.rb
Allow `Jets.once` to be called in a [simple function](https://rubyonjets.com/docs/functions/) without bombing in the TmpLoader.
https://community.rubyonjets.com/t/accessing-jets-models-in-simple-functions/288/5
Patch
=> dont bomb in TmpLoader when Jets.once called in simple function

lib/jets/builders/ruby_packager.rb
Removing projects `.bundle` as part of jets deploy ruby packaging instead of global `BUNDLE_IGNORE_CONFIG=1`. 
This allows `~/.bundle/config` to be respected. 
This is useful if you have private gems sources that require authentication. Example:
bundle config gems.myprivatesource.com user:pass
Was brought up in Gitter chat: https://gitter.im/tongueroo/jets (unsure how to link to specific post)
Patch
=> remove .bundle/config instead of BUNDLE_IGNORE_CONFIG=1

lib/jets/stack/main/dsl/kinesis.rb
Couldn't find test for the other DSL methods... but maybe I'm wrong?
I couldn't find a place where the other DSL methods are documented. Please point me to that if that exists and I'll be happy to help.
This allows us to easily add kinesis stream to a project.
We were just trying jets for the first time and we would like to have a quick way to create a kinesis stream.
minor
=> Add kinesis_stream dsl method.

docs/_docs/extras/deploy-with-mfa.md, jets.gemspec, lib/jets/aws_services.rb
This is a 🧐 documentation change. 
Add MFA support for standard IAM users.
* https://github.com/tongueroo/jets/issues/213
* https://github.com/tongueroo/jets/pull/388
Patch
=> MFA Support

docs/_docs/database/activerecord.md, docs/quick-start.md
Update docs to note how to use a different database adapter.
#404
=> add note about database adapter to quick start, also link to more docs

lib/jets/commands/db/tasks/dummy/app.rb, lib/jets/generator.rb
Really appreciate all the hard work that's gone into making this neat framework. Hoping the following contribution helps in some small way. If there's anything you'd like me to change, please let me know!
----
When using the `jets generate model` command with a *references* field (for example, `jets generate model post user:references title:string`), I'm seeing the following error:
```
NoMethodError: undefined method `application' for Rails:Module
```
The issue seems to stem from the fact that [this commit](https://github.com/rails/rails/commit/8b4d344815655027d9f7584c0a59271dce8f1d5a#diff-06ee83dd4b3615868328dd430573327bR147) added a check that references `Rails.application` in the …
=> Fix error with 'references' column in 'jets generate model'

lib/jets/cfn/builders/parent_builder.rb
Enable SSE-S3 Encryption on the parent jets s3 bucket by default.
Patch
=> enable sse-s3 encryption on parent s3 bucket by default

jets.gemspec, lib/jets/controller/middleware/reloader.rb
Fixes hot-reloading for projects using ActiveRecord Single Table Inheritance , STI , in development mode.  
Handled by reloading all dependent gems with `Zeitwerk::Loader.eager_load_all`
Also, ensure using https://github.com/tongueroo/aws-mfa-secure version ~> 0.4.0 which needed a fix for 
eager_load_all to work.
https://community.rubyonjets.com/t/subclassnotfound-single-table-inheritance-error-due-to-unexpected-class-reloading/338
Patch
=> Development hot-reloading for projects using ActiveRecord STI Issue

lib/jets/application/defaults.rb, lib/jets/controller/middleware/reloader.rb, lib/jets/middleware/default_stack.rb
* defaults to true in development mode
* allow override in case want behavior to be different on AWS Lambda
This also reverts #412 which was not the proper fix
Add `config.hot_reload` option to allow override of default behavior. 
Hot reloading causes issues with STI. Related #412
Make sure hot-reloading still works.
1. start server
2. change file
3. refresh url and see the changes without having to restart
Patch
=> add config.hot_reload option to allow override

lib/jets/overrides/rails/rendering_helper.rb
Haml gem injects a middle layer between `render` and `Jets::RenderingHelper`. https://github.com/haml/haml/blob/master/lib/haml/helpers/action_view_mods.rb#L6. Because of this, `folder` cannot be extracted correctly from callers.
=> Fix `render` doesn't recognize relative partial path with haml

lib/jets/overrides/rails/rendering_helper.rb, spec/lib/jets/rails_overrides/rails_overrides_spec.rb
* also fix specs and account for case
* related #410
More narrowly scope the search for caller_lines to find the template name in the overridden rails render method.
#410 
1. Add `gem 'haml-jets'` to Gemfile
2. In a view, render out to another partial that is haml
3. It should now find the partial properly and render successfully
Patch
=> more narrow check for /gems/ for caller_lines search

docs/_docs/deploy.md, docs/_docs/install.md, docs/quick-start.md, spec/spec_helper.rb
Update docs to state that the aws cli is required to be installed. 
#403
N/A
N/A
=> docs: aws cli install required, also note how to deploy to multiple regions

lib/jets/commands/call.rb
Maybe doing ```ENV["AWS_REGION"]``` as the second option is not really required, but I just wanted to fetch the information on all the possible ways before falling back to 'us-east-1'.
Also I searched through the project and Aws.config[:region] only occurs here. So no further action needed. 
Correct approach to get selected region implemented. Seen at https://github.com/aws/aws-sdk-ruby/issues/1042, ```Aws.config[:region]``` doesn't respond with correct values as long as it's not loaded by another client.
https://github.com/aws/aws-sdk-ruby/issues/1042
https://github.com/tongueroo/jets/issues/416
closes #416
Try using ```jets call``` with another region configured in ~/.aws/config without initialising any other part of the project.
2.3.8 > 2.3.9
=> 'jets call' honours region configuration

lib/jets/internal/app/controllers/jets/mount_controller.rb
Now setting env["SCRIPT_NAME"] = mount_at
This value is set when building a env variable for rack. 
This change prevent assets path from breaking when we mount gems in Jets Application.
I faced this problem when I was accessing split gem's web interface. The CSS and JS files were not loading and throwing 404 error. Split is a Sinatra based AB testing platform. It uses url() method for defining the assets path. Which uses ENV["SCRIPT_NAME"] when constructing the assets path.  ENV["SCRIPT_NAME"] is set to empty string. 
So, suppose if I mount the gem at 'admin/split' the assets path should be 'http://localhost:3000/admin/split/style.css' but it is generating 'http://localhost:3000/style.css' and is breaking.
When I tested the same scenario within Rails application, …
=> Setting ENV["SCRIPT_NAME"] same as mount_at value.

lib/jets/internal/app/controllers/jets/mount_controller.rb
Made some correction in the code with respect to my last commit.
Now adding a forward slash ('/') to script_name variable as we get in Rails.
=> Adding forward slash before path in sript name env variable

lib/jets/commands/new.rb, lib/jets/commands/templates/skeleton/config/database.yml.tt
Use underscore in the db name for the generated `config/database.yml` instead of dashes.  Example:
```yaml
database: my_api_development
```
VS
```yaml
database: my-api_development
```
=> use underscore for database name in database.yml

lib/jets/overrides/rails/url_helper.rb
Allow any `url_for` and hence view helpers to work for any model that is ActiveModel compatible.
Noticed url helpers would not when working with DynamoDB based models and standard the `form_with` tag. 
Use a ActiveModel and create a form.
=> url_for: allow any activemodel compatiable object to work

lib/jets/builders/code_builder.rb, lib/jets/commands/deploy.rb
This is a 🐞 bug fix
Fix subtle bug when code doesn't get uploaded from newly generated shims. 
Tricky one to reproduce:
1. deploy 
2. make a change that will only affect the generated handler shims. IE: Add a custom domain
3. deploy again - notice that the code does not get re-uploaded as generated shims are not included in the md5 checksum calculation
After this change, code uploads just fine.
Patch
=> fix subtle bug when code doesnt get uploaded from newly generated shims

docs/_docs/routing/custom-domain.md, lib/jets/resource/route53/record_set.rb
Adds ability to specific route53 host zone to use with `hosted_zone_id`. Docs: https://rubyonjets.com/docs/routing/custom-domain/ Example:
```ruby
Jets.application.configure do
config.domain.cert_arn = "arn:aws:acm:us-west-2:112233445577:certificate/8d8919ce-a710-4050-976b-b33da991e7e8" # String
config.domain.hosted_zone_name = "coolapp.com" # String
config.domain.hosted_zone_id = "/hostedzone/Z2E57RZEXAMPLE"
end
```
Fixes #381
Add `hosted_zone_id` and deploy.
Patch
=> add hosted zone id support

lib/jets/controller/rendering.rb
When CloudFront is in front of API Gateway, the actual host is in `headers["origin"]`. Favor `headers["origin"]` over `headers["host"]`, so things like `redirect_to` maintains the same domain.
Test app with CloudFront in front of API Gateway.
Patch
=> use headers origin for actual host in case of cloudfront in front

lib/jets/builders/code_builder.rb, lib/jets/job/dsl/dynamodb_event.rb
When running `jets build` with JETS_BUILD_NO_INTERNET set, a couple things were still trying to hit AWS. This fixes those things.
Some people want to simply produce the zip, ex: if deploying to aws via other means, such as Terraform.
Run this on a machine without aws credentials setup:
```jets new api
cd api
JETS_BUILD_NO_INTERNET=true jets build```
Minor version or less
=> Jets build no internet

lib/jets/lambda/function_constructor.rb, lib/jets/tmp_loader.rb, spec/lib/jets/controller/response_spec.rb
Fix simple functions being loading Jets outside of Jets.
```ruby
require 'bundler/setup'
require 'jets'
Jets.once
def lambda_handler(event:, context:)
...
end
```
https://community.rubyonjets.com/t/accessing-jets-models-in-simple-functions/288/7
Deploy simple functions.
Patch
=> fix simple function tmp_loader

docs/_docs/events/sqs.md
Remove out-of-date note about FIFO Queue
AWS Lambda now supports Amazon SQS FIFO as an event source.
https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-amazon-sqs-fifo-event-source/
=> Remove out-of-date note about FIFO Queue

CHANGELOG.md, lib/jets/resource.rb, lib/jets/resource/api_gateway/method.rb, lib/jets/resource/api_gateway/resource.rb, spec/lib/jets/resource/api_gateway/method_spec.rb
When ApiResource has a long name, it is being truncated by the
generator to match ApiGateway requirements of having resource names
no longer than 64 (62) characters.
Jets::Resource::ChildStack#controller_params when generating
templates are identifying resource ids by postfix, like Resource,
Authorizer or RootResourceId. Truncating was removing that postfix,
making it impossible to be properly recognized by that mechanism and
in effect, a failed deployment.
This fix changes the truncating code to make it shorter and keep
the postfix.
=> Fix ApiResources with long names not in template

lib/jets/dotenv.rb, spec/fixtures/apps/franky/.env.test.local, spec/fixtures/apps/franky/.env.test.remote, spec/lib/jets/dotenv_spec.rb
*.local files where loaded when JETS_ENV_REMOTE=1 was set, which isn't the behavior one would expect.
Now *.local and *.remote files are mutually exclusive.
See discussion here:
https://community.rubyonjets.com/t/why-is-local-environment-loaded-when-jets-env-remote-1/378
Two new .env files were added to spec/fixtures/apps/franky.  Simply run "bundle exec rspec" and spec/lib/jets/dotenv_spec.rb will ensure that only *.local or only *.remote files are loaded by Dotenv.
=> Ignore *.local files when JETS_ENV_REMOTE=1

docs/_docs/initializers.md, lib/jets/booter.rb, spec/fixtures/apps/franky/config/initializers/01_initializer.rb, spec/fixtures/apps/franky/config/initializers/02_initializer.rb, spec/lib/jets/application_spec.rb
Hello, I've added a call to `#sort` when globbing the initializers. The resulting paths from the `#glob` call are returned in the order given back by the OS, which isn't necessarily alphabetical.
This was just something silly I was burned by. I found this recent discussion while researching the issue: https://bugs.ruby-lang.org/issues/8709
I've added initializers to the test app, and timestamp when they're invoked. If there is a better way to test, please let me know and I'll adjust.
This could be patch-level change.
=> Forcing sort of initializers

lib/jets/internal/turbines/jets/mailer.rb
Sometimes the Lambda environment fails to load the actionmailer turbine initializer. Unsure exactly why. This is a temp fix to, at least, prevent the initializer from crashing. Will have to investigate why this is happening more thoroughly.
https://community.rubyonjets.com/t/undefined-method-default-url-options-for-nil-nilclass/400
Just regular deploy and test.
Patch
=> temp fix for actionmailer turbine initializer

lib/jets/turbo/templates/config/database.yml
Fixes `encoding` in `jets/turbo/templates/config/database.yml` by setting it according to the DB adapter in the current database config. `unicode` for postgresql otherwise `utf8mb4` (mysql)
Fixes https://github.com/tongueroo/jets/issues/441
Bump patch version.
=> Fix Jets turbo DB encoding

docs/_docs/app-config/filtering_params.md, docs/_includes/subnav.html, lib/jets/application/defaults.rb, lib/jets/controller/base.rb, lib/jets/controller/parameters_filter.rb, lib/jets/controller/params.rb, spec/lib/jets/controller/base_spec.rb, spec/lib/jets/controller/parameters_filter_spec.rb, spec/lib/jets/controller/params_spec.rb
This is a 🙋‍♂️ feature or enhancement
This pull request adds support for parameters filtering in order to filter sensitive information out of the logs. ActiveSupport::ParameterFilter was used for this task.
Related to this issue: https://github.com/tongueroo/jets/issues/399
I created this repo https://github.com/josediaz16/jets_demo following guides from https://github.com/tongueroo/jets/blob/master/readme/testing.md.
I had some troubles during testing: 
- I had to add `cfn_status` to Gemfile because an error like mentioned [here](https://github.com/tongueroo/jets/pull/400) occurs. 
- When running the local integration tests I got 4 failures because of `InvalidAuthenticityToken`, but the same happens using current version of Jets, I wouldn't think this PR affects that.
=> Allow parameters filtering

lib/jets/router.rb, spec/lib/jets/router_spec.rb
/posts/:id/comments/new and /posts/:id/comments/:id both contain a `:`
and both have the same length, so it is nondeterministic which one will
match with the current implementation of ordered_routes.
At the moment for nested resources defined like this
```
nested_resources :posts do
nested_resources :comments
end
```
the router can (and for me at least will) send `/posts/1/comments/new` to `CommentsController#show` instead of `CommentsController#new`, because routes for both capture a variable and the paths are equally long.
This PR changes it so that capturing more variables means that the route is considered less specific and will be checked after more specific routes have been tried.
Running the test added by this PR on the master branch demonstrates the issue (at …
=> Order routes so that nested resources always work

lib/jets/commands/build.rb
Prints out the location of CloudFormation templates after `jets build`
Closes https://github.com/tongueroo/jets/issues/442
Trivial change.
Patch because I think it's a tiny enhancement.
=> Print Cfn templates location after build

lib/jets/builders/code_builder.rb
Fixes afterburner mode by:
* calculate_md5s before generate_shims to fix handlers/data.yml
Related #424 - This PR introduced the bug. Unsure about it being the right fix.
Deploy rails app with Afterburner. Confirm working.
Patch
=> Fix afterburner mode

lib/jets/builders/code_builder.rb
Recently `jets build` command is failed with `Aws::S3::Errors::Forbidden`.
Maybe someone created `bucket-does-not-yet-exist` as bucket name.
So `exist_on_s3?` method in `code_builder.rb` throw `Aws::S3::Errors::Forbidden` error.
Below is the log when I failed to build
```
Bundle install success.
Tidying project: removing ignored files to reduce package size.
=> rsync -a --links /tmp/jets/yahb-jets/stage/code/vendor/gems/ruby/2.5.0/ /tmp/jets/yahb-jets/stage/opt/ruby/gems/2.5.0/
=> Replacing compiled gems with AWS Lambda Linux compiled versions: /tmp/jets/yahb-jets/stage/opt
Checking projects gems for binary Lambda gems...
=> Generating shims in the handlers folder.
bundler: failed to load command: jets (/Users/kuchitama/.anyenv/envs/rbenv/versions/2.5.7/lib/ruby/gems/2 …
```
=> Handle forbidden error from s3

docs/_docs/install.md, jets.gemspec
Looks like on 4/16/2020 AWS Lambda rolled out an update that upgrades json to a specific version, as a part of a security upgrade. This breaks Lambda functions that have different json in their `Gemfile.lock` from the AWS Lambda runtime. By removing the json gem from the jets dependencies, it loosens up the version of json being used. This helps to mitigate future updates from AWS Lambda.
Note, this will not prevent jets project `Gemfile` or other gems in there that specify json from locking to a specific version of json. However, at least, jets won't be the gem that causes json to be bundled into Gemfile.lock. So there's some mitigation here.
https://community.rubyonjets.com/t/init-error-when-loading-handler-errortype-init-gem-lo …
=> remove json gem dependency to loosen Gemfile.lock

lib/jets.rb, lib/jets/builders/code_builder.rb, lib/jets/builders/ruby_packager.rb, lib/jets/commands/import/base.rb, lib/jets/commands/main.rb, lib/jets/commands/new.rb, lib/jets/core_ext/bundler.rb, lib/jets/rack_server.rb, lib/jets/turbo/rails.rb
* removes bundler deprecation warning
Removes bundler deprecation warning. Keep old versions of bundler working for now.
Fixes #449 
Deploy and make sure app is still working on Lambda.
Patch
=> use Bundler.with_unbundled_env

docs/_docs/database/activerecord.md
I was going through the docs and think you may have forgot to add the db:create step of the set-up process.
This is a 🧐 documentation change. 
- [x ] I've adjusted the documentation (if it's a feature or enhancement)
Just a tiny update to the docs to include the db:create step on the ActiveRecord page.
No related issues.
No testing needed as it's just a documentation update.
=> Update activerecord.md to include db:create step

lib/jets/commands/templates/skeleton/Gemfile.tt
Fixed repeating text for description of `gem "jetpacker"` in _Gemfile_.
=> Fixed description for "jetpacker" gem in Gemfile

docs/_docs/extras/minimal-deploy-iam.md
Added missing permissions to the least-privilege deployment permissions documentation.
I had to add both the `lambda:UpdateFunctionCode` and `lambda:UpdateFunctionConfiguration` actions in order to successfully run `jets deploy`.
N/A
I visually verified the change after running `bin/web` in the docs directory.
=> Update lamdba permissions for minimal-iam-policy doc

jets.gemspec, lib/jets/resource/api_gateway/method.rb, lib/jets/resource/api_gateway/resource.rb, spec/lib/jets/resource/api_gateway/method_spec.rb, spec/lib/jets/resource/api_gateway/resource_spec.rb
When defining a dotted URL, CloudFormation failed during deployment with the following message
```
Template format error: Resource name V1.2PostsShowCorsApiMethod is non alphanumeric.
```
For example, if we'd like to define a path like `/v1.2/posts/123`, Jets will fail to deploy it.
So we'll fix that.
- none in particular
`bundle exec rspec spec/lib/jets/resource/api_gateway/resource_spec.rb spec/lib/jets/resource/api_gateway/resource_spec.rb`
or
Define route that contains dot.
```ruby
Jets.application.routes.draw do
scope prefix: :'v1.2' do
get 'posts/:post_id', to: 'posts#show'
end
end
```
and deploy to AWS.
patch
@tongueroo Could you check it?
=> Allow to define route that contains dot

lib/jets/cfn/upload.rb
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html
This is a 🙋‍♂️ feature or enhancement. 
By default, cloudfront will not serve assets compressed. Even the ones generated pre-compressed with a webpacker build. However, if you set the content type in the s3 bucket with certain types, cloudfront will automatically compress the object when serving if the client indicates it can accept compressed content.
=> set content type on upload by using extension so cloudfront will compress when serving

lib/jets/spec_helpers/controllers/request.rb, spec/lib/jets/spec_helpers_spec.rb
support nested query params in the tests
#516 
we have an API in jets using [JSON:API specification](https://jsonapi.org/format/#fetching-filtering), when we try to send a request like this 
```ruby
get "/comments", query: { filter: { post: [1, 2], author: 12 } } # /comments?filter[post]=1,2&filter[author]=12
params['filter'] 
=> "{:post=>[1, 2], :author=>12}"
```
the controller receives the nested query params as a string with a bad format
```ruby
bundle exec spec/lib/jets/spec_helpers_spec.rb
```
=> support nested query params in tests

lib/jets/commands/templates/skeleton/config/application.rb.tt
Fix a typo of `$strerr` instead of `$stderr` in a template used by the new-app generator.
https://github.com/boltops-tools/jets/pull/140
=> Fix Jets::Logger strerr -> stderr typo

lib/jets/router/dsl.rb, lib/jets/router/scope.rb, spec/lib/jets/router_spec.rb
Added `param` to `Jets::Router::Scope` options, which allows correct retention of custom path parameter names in resources (and nested resources).
Closes #510.
`bundle exec rspec spec/lib/jets/router_spec.rb`
I recommend a patch version change.
=> Fix custom resource path parameter names

lib/jets/controller/params.rb, spec/lib/jets/controller/params_spec.rb
Rails decodes query/path/body parameters.
This PR adds decode process.
Nothing
Please see [first commit test result](https://app.circleci.com/jobs/github/tongueroo/jets/3185). Then check [second commit fixes it](https://app.circleci.com/pipelines/github/tongueroo/jets/95/workflows/21b7944c-8795-4ce9-a8d1-f7516019a818/jobs/3186/steps).
=> Add unicode body/path/query parameter decode in params

lib/jets/application.rb, lib/jets/application/defaults.rb, spec/lib/jets/application_spec.rb
Adds a default Time.zone (UTC seems a reasonable default)
Also allows user to change the the time zone via `config.time_zone` 
First PR, please advise :)
https://github.com/boltops-tools/jets/issues/427
Config the time zone by setting `config.time_zone = zone_name_here` in `config/application.rb`
Reference list: https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html
Call Time.zone from application code.
=> Add config for Time.zone

lib/jets/application.rb, lib/jets/application/defaults.rb, spec/lib/jets/application_spec.rb, spec/lib/jets/resource/iam/class_role_spec.rb, spec/lib/jets/resource/iam/function_role_spec.rb
* Tightens default app-wide IAM policy to no longer allow `ListAllMyBuckets` and `HeadBucket` to all buckets in the AWS account
* Makes it easier to override the app-wide IAM policy and its defaults
Resolves https://github.com/tongueroo/jets/issues/455
Major.
Apps that override `iam_policy` currently will also need to update `default_iam_policy` after this change to maintain identical behavior.
I'm open to toning down the changes to avoid this.
=> Improve iam_policy configuration

docs/_docs/app-config/request_logging.md, lib/jets/controller/base.rb, spec/lib/jets/controller/base_spec.rb
[x ] I've added tests (if it's a bug, feature or enhancement)
[x ] I've adjusted the documentation (if it's a feature or enhancement)
Move the web request completion log to its own method. This allows developers to more easily customize logs.
Resolves #478
rspec
=> Create request completion log method

lib/jets/commands/call.rb, lib/jets/commands/help/call.md, lib/jets/commands/main.rb, spec/lib/jets/commands/call_spec.rb
When `jets call` is run for a function that requires too long execution time, the timeout error happens and the lambda client makes requests to retry.
Sometimes users don't want the behavior.
Create and deploy a function that requires to execute more than 1 sec, and then call the function with `--read_timeout 1 --retry_limit 0`
=> Add retry_limit and read_timeout options

lib/jets/spec_helpers/controllers/request.rb, spec/lib/jets/spec_helpers_spec.rb
https://github.com/tongueroo/jets/blob/91a7bf7f/lib/jets/spec_helpers/controllers/request.rb#L49
```ruby
params.query_params.each do |key, value|
json['queryStringParameters'] ||= {}
json['queryStringParameters'][key.to_s] = value.to_s
end
```
In Request class of spec_helper, value is converted to string.
But the value can be array or hash. It must not convert to string.
n/a
Please see [first commit test result](https://app.circleci.com/pipelines/github/tongueroo/jets/86/workflows/6849f173-341e-4fb6-aec4-402f84822770/jobs/3177/steps). Then check [second commit fixes it](https://app.circleci.com/pipelines/github/tongueroo/jets/87/workflows/7fe5bddd-8c69-44c8-97ba-bdaf5f188c59/jobs/3178/steps).
Nothing
=> Fix queryStringParameters handling for nested value in spec_helper

lib/jets/router/dsl.rb, lib/jets/spec_helpers/controllers/request.rb, spec/lib/jets/spec_helpers_spec.rb
Spec helper of Rails support UTF-8 path notation ( https://github.com/rails/rails/blob/49baf092/actionpack/test/dispatch/routing_test.rb#L4217-L4234 ).
This PR adds its support.
Nothing
Please see [first commit test result](https://app.circleci.com/pipelines/github/tongueroo/jets/92/workflows/ae8d89f3-6873-494b-95d4-d758cdc19abe/jobs/3183/steps). Then check [second commit fixes it](https://app.circleci.com/pipelines/github/tongueroo/jets/93/workflows/5275d164-fac1-4d67-9914-fb05a82a0f5d/jobs/3184/steps).
=> Add unicode test for spec_helpers test

lib/jets/builders/gem_replacer.rb, lib/jets/builders/ruby_packager.rb
Looks like in a recent versions of either ruby or bundler changed native gems detection, specifically on macosx. Additionally, new version of bundler (tested bundler 2.2.5), writes macosx platform info to the Gemfile.lock. 
This PR fixes these issues.
#523 
Go through quick start on macosx.
Patch
=> fix native gem detection

jets.gemspec, lib/jets/builders/gem_replacer.rb, lib/jets/builders/ruby_packager.rb
Handled this in Jets v3. Thought this was a ruby 2.7 vs ruby 2.5 issue but it's more specific than that. It's has to do with specifically how some gems like nokogiri now maybe bundles. Anyway, backported this fix.
#523 #524 
https://github.com/boltops-tools/serverlessgems/pull/1
Deploy Jets app that uses the nokogiri gem.
Patch
=> 2.3.x gem detection

jets.gemspec, lib/jets/internal/app/controllers/jets/public_controller.rb
Use mini_mime gem instead
closes #535
Regression: Deploy jets app and make sure it still works. 
Patch
=> use mini_mime instead

lib/jets/overrides/rails/migration_checker.rb
this pr fixes the following deprecations warnings
ref
https://github.com/boltops-tools/jets/issues/538
=> FIX DEPRECATION WARNING: connection_config is deprecated

jets.gemspec, lib/jets/builders/md5_zip.rb
Today I needed to add a custom layer to my jets project. After I generated the custom layer, I tried to add the new layer but I received the following error on the aws console: "Layer conversion failed: Some files need to be overridden by layers but don't have write permissions;"
This error occurs because in the layer generated by the Jets, the folders do not have write permission per group.
I’ve fixed this error by changing the line below the md5_zip.rb file:
> command = "cd #{@path} && zip --symlinks -rq #{zip_file} ."
to:
> command` = "cd #{@path} && **chmod -R 755 .** && zip --symlinks -rq #{zip_file} ."
You shall create a custom layer with the following structure:
.
|_lib
|_ruby
|_gems
|_2.7.0
|_**
After that, try adding the custom layer on the lambda.
3.0.3
I …
=> Error custom layer

docs/_docs/extras/minimal-deploy-iam.md, docs/_docs/install.md, docs/quick-start.md
I was tripped up when running through the Quick Start in this way:
* I went to the Quick Start page.
* I started running the commands.
My issues were:
* I was running Ruby 3, which installed an old, pre-v1 version of `jets`.
* I had not configured the `aws` CLI so `jets deploy` failed.
This pull request edits the docs to help avoid this mistakes by:
* Noting that there are prerequisites and linking to the Install section for more details.
* Referencing the IAM policy page before `aws-cli` install instructions
so that the reader creates the policy, group, and user before configuring CLI.
=> Add instructions for aws-cli prerequisite

lib/jets/resource/lambda/function.rb
We have an enterprise app running on jets but we have a custom layer for this application, when we try to add our custom layer the deployments fail because it exceeds the layer limit on lambda, I did a quick research and I realized that when I add a custom layer, Jets stills uploading its layer.
ref https://github.com/boltops-tools/jets/issues/541
=> doesn't include the Jets layer when config.gems.disabled = true

lib/jets/aws_info.rb
This PR catches `Aws::STS::Errors::InvalidClientTokenId` thrown in `aws_info.rb` when attempting to `get_caller_identity`.
From a clean install of `jets` on my machine, I followed the instructions but was unable to run `jets db:create` after using the `--database=postgresql` and `--mode api` options to setup a new jets app.
After testing locally, I am able to run both `jets db:create` and `jets server` with this change.
Remove `~/.aws/credentials` and run `jets new test_app --mode api --database=postgresql`.  After bundling, you should be able to run `jets db:create` and `jets server` successfully.
Bump to `3.0.6`
=> Handle Errors::InvalidClientTokenId when get_caller_identity fails

lib/jets/resource/lambda/function.rb, spec/fixtures/apps/franky/app/controllers/articles_controller.rb, spec/lib/jets/resource/lambda/function_spec.rb
Jets allows us to specify a description as a function property, but even if we do, it will not be reflected in the Lambda function and the default description will be used(e.g. `PostsController#index`).
It seems that the specified description is overwritten with the default description when creating the CloudFormation template.
So, I propose to modify behavior to use specified description if there is.
None
1. Reflect the changes contained in this PR in your local Jets gem.
2. Clone the demo app from my repo. This app has only one controller and only one action is defined, with a description for that action.
- Run `$ git clone git@github.com:kfukai23/demo.git`
3. Run `$ jets deploy`.
4. Open the list of Lambda functions in the AWS console and verify that the …
=> Use description specified in function properties exactly

lib/jets/controller/rack/adapter.rb, spec/lib/jets/controller/rack/adapter_spec.rb
This fixes a bug in which multivalue response headers were set in a single header.
https://github.com/boltops-tools/jets/issues/555
Since jets locally uses puma, this bug is only apparent in an AWS environment.
`set_header('My-Header', ['a', 'b'])` should yield 2 seperate response headers of `My-Header`, one with value `a` and one with value `b`
=> allow multi value response headers

lib/jets/builders/tidy.rb
Do not include files in the `.jetsignore` file in the deployment package.
#561
Add a file to `.jetsignore` and confirm it's not in the zip package.
Patch
=> respect .jetsignore also

docs/_docs/extras/jetsignore.md, docs/_includes/sidebar.html, lib/jets/builders/tidy.rb
Adjust default `.jetskeep` handling to allow ignoring files like `vendor/bundle`. This helps to keep the zipfile size down.
* #571 In some environments, a /tmp/jets/[project]/stage/vendor/bundle directory remains and is included in zip, causing deploys to fail
* #573 exclude code/vendor/bundle from deploy stage if it exists 
1. Create a `.jetsignore`
2. Add files to it
3. Deploy and confirm that the files are not part of the Lambda zipfile package. You can do this by looking at the Lambda console and looking at the file tree.
Patch
=> Jetsignore

lib/jets/core.rb
I'm not sure why this changed, but after a dependency update my HTML rendering pages failed because the webpacker helpers were not available in ActionView::Base. This fixed the issue.
=> fix missing webpacker helpers

lib/jets/resource/api_gateway/base_path/function.rb
This PR resolves two bugs when using a custom domain for API Gateway:
-  Any custom lambda layers used would be ignored
- if `config.gems.disable = true`, continue to use `config.lambda.layers`.
Stumbled upon this one when trying to use a custom domain for API gateway via `config.domain.*` but it was perpetually failing as `JETS_AGREE=no` and `config.gems.disable = true`, meaning it was trying to use an incomplete layer (the default Jets layer) as opposed to a custom provided layer. 
1. Prepare a lambda layer that _isn't_ namespaced by Jets.
- For brevity + speed sake you can generate the lambda layer via the serverlessgems.com service, download and then re-upload under a new name. Key thing here is the arn isn't the one prepared by Jets
2. Configure …
=> Fixes API Gateway base path Lambda not respecting various config opts

docs/_reference/jets-delete.md, lib/jets/commands/help/delete.md
This is a 🧐 documentation change. 
Updates the documentation for `jets delete`. The documentation shows that you should be able to skip the prompt with `--skip` but the code shows that this is actually `--yes`
https://github.com/boltops-tools/jets/blob/35bb5a40148074ae03f03b85b16e63707df90970/lib/jets/commands/delete.rb#L116-L122
N/A
=> Update "jets delete" documentation to be --yes instead of --skip

lib/jets/builders/md5_zip.rb, spec/lib/jets/builders/md5_zip_spec.rb
NumberHelper has been moved to active support from actionview. this is sometimes causing jets builds to fail.
https://github.com/boltops-tools/jets/issues/579
Run `jets build`
=> Use active support instead of actionview

lib/jets/middleware/default_stack.rb, spec/lib/jets/middleware/stack_spec.rb
Always use Shotgun::Static middleware. This allows static assets and images to be service in JETS_ENV=test mode.
Patch
=> use Shotgun::Static middleware always

lib/jets/controller/rendering.rb, spec/lib/jets/controller/rendering_spec.rb
Don't overwrite `content_type` when rendering json or xml with `content_type` specified.
example:
```ruby
render json: {my: "data"}, content_type: "application/json;charset=UTF-8"
```
None
```ruby
render json: {my: "data"}, content_type: "application/json;charset=UTF-8"
```
=> Don't overwrite content_type  when rendering json or xml with content_type specified

docs/_docs/extras/elb-server-override.md, lib/jets/controller/middleware/local.rb
- This is a 🙋‍♂️ feature or enhancement.
- This is a 🧐 documentation change. 
This PR adds an override flag (`JETS_SERVER_ELB_OVERRIDE`) so if `jets server` is being fed traffic through an ELB, we get the same behaviour as if we were hitting it locally or through another load balancer.
As part of some internal work going on where I work, there's been a need to create a stronger feedback loop with a copy of various services, including one that uses Jets. These services can be fed through an ELB (typically an ALB) and will generally work as they would as if in a production environment however, Jets appears to diverge in its behaviour if we're behind an ELB - 
https://github.com/boltops-tools/jets/blob/1ccd80b49d22bfdd53fa22f998b6faae37d8fe33/lib/jets/controller/middleware/local.rb#L71-L74 …
=> Adds an override flag to change behaviour when Jets is behind an ELB running Jets Server

lib/jets/internal/app/functions/jets/base_path_mapping.rb
Adjust retry and exponential backoff for base path mapping in case of rate limit issues with larger applications. 
2 ** c.retries * c.config.retry_base_delay
The max delay will be 2 ** 7 * 0.6 = 76.8s
Running into deploy issues with larger apps and custom domains.
Deploy a large app, 150+ lambda functions
Patch
=> custom domain: adjust rate limit for base mapping

lib/jets/aws_services.rb, lib/jets/commands/clean/log.rb, lib/jets/commands/delete.rb, lib/jets/commands/deploy.rb, lib/jets/resource/api_gateway/rest_api/routes/change/base.rb
Configure jets AWS clients only with longer retry settings to handle rating limiting issues. 
The aws-sdk-core has exponential backup with this formula:
2 ** c.retries * c.config.retry_base_delay
So the max delay will be 2 ** 7 * 0.6 = 76.8s
Before it the `aws_config_update!` would do it globally and possibly affect user app code.
Folks with large jets apps, 150+ lambda functions, are running into rate limiting issues. This should substantially reduce the issues as all Jets AWS clients are being handled. This also cleans up the code a lot.
Deploy large jets app, 150+ lambda functions, over and over.  Note: The rate limits seem to only occur right after deploying the full app from scratch first and then deploying again. This is …
=> Improve Rate Limit Handling

lib/jets/builders/ruby_packager.rb
This fixes https://github.com/boltops-tools/jets/issues/594 where the PLATFORMS section of Gemfile.lock was not being properly overwritten when multiple values were declared, as in my case. For instance:
```
PLATFORMS
x86_64-darwin-18
x86_64-darwin-19
```
was resulting in:
```
PLATFORMS
ruby
x86_64-darwin-19
```
when for Lambda purposes it needed to be:
```
PLATFORMS
ruby
```
This resolves.
Change the PLATFORMS section of Gemfile.lock to have multiple declarations such as above, then download the code from AWS after deployment to see that it should only reflect the single value `ruby`.
Whatever the next reasonable release is.
=> Rewrite PLATFORMS section to specify Ruby only

jets.gemspec, lib/jets.rb, lib/jets/autoloaders.rb, lib/jets/booter.rb, lib/jets/commands/templates/skeleton/Gemfile.tt, lib/jets/stack.rb
Support zeitwerk 2.5.  
* The `jets new` command generates a Gemfile that pins to `gem "zeitwerk", ~> 2.5.0`
* The `jets.gemspec` also requires zeitwerk 2.5.x. 
* Important: Zeitwerk does not support the old interface used in jets 3.0.2. IE: zeitwerk_loader.preload (old and has been removed) zeitwerk_loader.on_setup (new and takes in a block instead of a string).
* Users must upgrade to zeitwerk 2.5.x when upgrading to jets 3.1
When upgrading to jets 3.1, you should 
1. unpin zeitwerk in your Gemfile and pin it to `gem "zeitwerk", ~> 2.5.0` or 
2. leave the version unpinned entirely and then run:
bundle update
Not supporting zeitwerk 2.4.x and below after jets 3.1
#601
Unpin zeitwerk in your jets project Gemfile and run bundle update.
Minor
=> support zeitwerk 2.5

jets.gemspec
Update the jets.gemspec required_ruby_version to `>= 2.5` and `< 3`. A little bit surprised the specifier allowed 2.7. Unsure why. Fixing it anyway.
Deploy jets app as sanity check
Patch
=> adjust required_ruby_version

lib/jets/cli.rb, lib/jets/commands/console.rb, lib/jets/commands/main.rb, spec/lib/jets/commands/console_spec.rb
Lets `jets console` accept environment as an argument. 
```
$ jets console sandbox
Jets booting up in sandbox mode! 
```
This really just uses the set_jets_env_from_cli_arg! hack. 
```
bundle exec rspec spec/lib/jets/commands/console_spec.rb
```
=> Jets Console accepts environment cli argument

jets.gemspec
Think it's better to have `>=` for most gem dependencies than `~>`, except for the rails components. 
Sanity check
Patch
=> use >= for most gem dependencies

lib/jets/commands/templates/skeleton/Gemfile.tt
Loosen the zeitwork dependency version in generated project Gemfile.
Ran into some warnings it whenever zeitwork doesn't match with the system installed one. Loosening it so warning goes away and probably less work for users overall.
Deploy demo jets app and make sure it works.
Patch
=> loosen zeitwerk  dependency in generated project Gemfile

docs/_docs/app-config.md, lib/jets/application/defaults.rb, lib/jets/resource/api_gateway/rest_api.rb, spec/lib/jets/resource/api_gateway/rest_api_spec.rb
We needed a private gateway with a vpc endpoint and wanted the CloudFormation stack to handle all of the configuration on its gateway
This PR implements a `config.api.vpc_endpoint_ids` configuration. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html
=> Implement vpc_endpoint_ids configuration

README.md
Exciting project! I've been looking for something like this for a long time.
In the first line of the Readme it currently says "Ruby and Lambda splat out a baby".
"Splat out" here seems incorrect - at least it read that way to me when I came across this repo. 
"Spat out" is possibly what you meant, but then writing something like that in line one of the Readme doesn't give a great impression!
How about "had a baby", which comes across much more positively and doesn't interrupt the user by making them think about "splat out" versus "spat out" versus "had"?
=> Readme: Replace "splat out" with "had" a baby

lib/jets/internal/app/functions/jets/base_path.rb, lib/jets/internal/app/functions/jets/base_path_mapping.rb
Been running into this super-edge case from time to time over the years. Essentially, if the BasePathMapping Custom CloudFormation resource Lambda function errors super early before it gets to the [cfn_response logic](https://github.com/boltops-tools/jets/blob/fccf6156b51f84cbd99a9f0c428904f86ee9684e/lib/jets/internal/app/functions/jets/base_path.rb#L9-L17) then the Lambda function will not have the opportunity to send a SUCCESS or FAILED status back to CloudFormation. This results in the Custom Resource waiting until it eventually times out. The timeout can take 3 hours!  
The super-edge case can be caused by an outdated rubygems install on ruby 2.7. See: https://community.boltops.com/t/could-not-find-timeout-0-3-1-in-any-of-the-sources/996
Quite annoying to track …
=> Base path mapping

lib/jets/builders/gem_replacer.rb, lib/jets/builders/ruby_packager.rb
Run `bundle check` right after `bundle install` to verify that gems are installed properly. This prevents the deployment getting all the way to AWS Lambda and the user finding out painfully post deployment.
Related: https://community.boltops.com/t/could-not-find-timeout-0-3-1-in-any-of-the-sources/996
Sanity check. Deploy demo app.
Patch
=> bundle check and prevent error from getting to aws lambda

lib/jets/builders/code_builder.rb, lib/jets/cfn/builders/interface.rb, lib/jets/internal/app/jobs/jets/preheat_job.rb, lib/jets/lambda/dsl.rb, lib/jets/preheat.rb, lib/jets/resource/iam/base_role_definition.rb, lib/jets/resource/iam/policy.rb
Fixes #440 
Also:
* Improves prewarming and fixes bugs by looking up functions to preheat cloudformation, this generalizes it and handles long function names.
* Create separate IAM Role and Policy to allow policies to reference lambda function without a circular dependency error.
* This can to require a blue/green deployment. It depends if the user has user `iam_policies` in their code.
Deploy an app with a name with a long enough name. IE:
```ruby
Jets.application.configure do
config.project_name = "some-very-very-really-long-super-long-app-project-name"
end
```
Deploy it:
jets deploy
Confirm that really long function names that get cut off and managed by CloudFormation still produce an IAM …
=> PreheatJob: fix function lookups and iam function permission

lib/jets/cfn/upload.rb
Remove debugging `puts "Uploading and setting content type for...`
Patch
=> log debug uploading and setting content type

lib/jets/application/defaults.rb
Make sure that the `Jets.logger` level is info by default. For some reason, on some systems, it did seem to be debug.
Patch
=> make sure logger level info is default

lib/jets/cfn/builders/api_gateway_builder.rb
Fixes #557
Know, it's 99% of the time bad to `rescue Exception` 😔 It's a bummer it cause issues for the users who were kind enough to provide detailed issue reports. Vaguely remember that was mentally spent from working on Custom Domain and Custom CloudFormation resources and used the rescue Exception. 🤦🏻‍♂️ It's been removed and using more targeted rescues now.
Related: Also, wanted to note: https://github.com/boltops-tools/jets/pull/640 Made some important hardening improvements to Custom Domain Custom CloudFormation Resource Lambda Function that handles the custom domain. This takes rollback times down from 3 hours to 3 minutes. This should save everyone time from these related issues.
* Related ticket …
=> Custom DomainHard fail on IAM permission error

lib/jets/cli.rb
Fixes https://github.com/boltops-tools/jets/issues/484
lib/tasks/custom.rake
```ruby
namespace :custom do
desc "Custom rake task with params."
task :task, [:arg1, :arg2] => :environment do |t, args|
puts "arg1: #{args[:arg1]}"
puts "arg2: #{args[:arg2]}"
end
end
```
Can run the custom task with params with jets now also.
$ jets custom:task[0,'foo']
arg1: 0
arg2: foo
Before only worked with rake:
$ rake custom:task[0,'foo']
arg1: 0
arg2: foo
The custom rake task also shows on up the help menu:
$ jets -h
...
Commands via rake:
jets custom:task[arg1,arg2]  # Custom rake task with params
jets db:create               # Creates the database from DATABASE_URL or config/database.yml for the current RAILS_ENV ...
jets db:drop                 # Drops the database from …
=> allow custom rake tasks with params to work with jets as well as rake command

lib/jets/cfn/builders/base_child_builder.rb
Fix validate function names regexp
Related https://github.com/boltops-tools/jets/pull/650
Patch
=> Validate lambda function names: fix regexp

lib/jets/resource/api_gateway/cors.rb
Fixes cors when authorizers also used. 
Simply removed the `@route.authorization_type` in the or assignment.
Cannot think of a case where we also want cors OPTIONS requests to also have to go through the authorizer.
Fixes #465
Deploy app that has both cors enabled and uses an authorizer.
* https://rubyonjets.com/docs/cors-support/
* https://rubyonjets.com/docs/routing/authorizers/
Patch
=> fix cors when using authorizers

lib/jets/internal/app/jobs/jets/preheat_job.rb, lib/jets/lambda/dsl.rb
Fix prewarming IAM Permission
Related https://github.com/boltops-tools/jets/pull/645
1. Deploy jets demo app
2. Use `jets console` to call lambda function: `Jets::PreheatJob.perform_now(:warm)`
3. Confirm by checking the CloudWatch logs on the demo-dev-jets-preheat_job-warm
Patch
=> fix prewarming iam permission

lib/jets/application/defaults.rb, lib/jets/internal/app/jobs/jets/preheat_job.rb, lib/jets/resource/iam/base_role_definition.rb
This is a 🐞 bug fix
* Add VPC policy permission to IAM role as inline policy
* Makes the IAM permission available everywhere immediately and avoids the race condition when creating lambda functions.
* Also add VPC IAM permission to jets preheat job.
Fixes #661
Deploy with VPC. See Docs: https://rubyonjets.com/docs/considerations/vpc/
Patch
=> fix vpc iam permissions

lib/jets/overrides/rails/common_methods.rb
This is a 🐞 bug fix
- [ X] The test suite passes (run `bundle exec rspec` to verify this)
When sending mail locally add_stage_name gets called but is nill. So only add stage name when request is present, this way mail is sent locally. 
https://github.com/boltops-tools/jets/issues/664
patch
4.0.5
=> Jeremiah-Parrack | only add add_stage_name when request is present

lib/jets/commands/help/runner.md, lib/jets/commands/main.rb, lib/jets/commands/runner.rb
I'm using the `jets runner` for various maintenance tasks (eg create or update data) and it would be very handy to be able to pass in cli args.
No
I didn't see jets runner tests. I've simply tested in on the cli, with inline Ruby and a test script.
No opinion about version.
Thanks for considering!
=> Add optional command args to the jets runner command.

lib/jets/application/defaults.rb, lib/jets/internal/app/jobs/jets/preheat_job.rb, spec/lib/jets/internal/preheat_job_spec.rb
Fixes the default IAM policy for Jets::PreheatJob
The IAM role for PreheatJob appears to have been broken in c36f87f15e42c91991a867c2b6b10d4054b0603e, resulting in errors on Lambda like this:
> Aws::Lambda::Errors::AccessDeniedException User: arn:aws:sts::652695076726:assumed-role/bot-dev-JetsPreheatJob-1OYM89-JetsPreheatJobIamRole-C7QgfgQgszTl/bot-dev-jets-preheat_job-warm is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:652695076726:function:bot-dev-admin_controller-db because no identity-based policy allows the lambda:InvokeFunction action
Basically, the generated `app-name-preheat-job-policy` was missing permission to invoke Lambda functions.
View the generated policy document in the Lambda console for the execution role …
=> Fixes IAM role permissions for PreheatJob

lib/jets/application/defaults.rb
Fixes Jets::PreheatJob IAM role. 
Related #670
Do a `jets deploy` sanity check
Patch
=> fix preheat warm job iam role reference

lib/jets/commands/templates/skeleton/Gemfile.tt
The new dynomite 2.0.0 requires jets v5. This pins dynomite to 1.2.7 so `jets new` with people using jets v4 will still work.
jets version
jets new demo # make sure this works
Patch
=> pin dynomite 1.2.7

lib/jets/resource/api_gateway/rest_api/routes/change/base.rb
Allow the route change detection to handle either `http_method` or `method` from the route state file.
Patch
=> handle option method or http_method from route state

lib/jets/cfn/resource/api_gateway/rest_api/logical_id.rb, lib/jets/cfn/resource/s3/jets_bucket.rb, lib/jets/command.rb, lib/jets/command/base.rb
Fix the prompt that warns user that the APIGW Rest API will be replaced and a new endpoint will be created. This was accidentally broken in Jets 5 as part of the command CLI restructuring.
Related https://github.com/rubyonjets/jets/issues/391
I hacked the Routes changed? method to return true in the gem to reproduce and it prompts correctly.
Patch
=> fix apigw gateway replacement warning prompt

lib/jets/job/base.rb
When doing rspec in local, one message keeps on showing: "INFO: Not on AWS Lambda. In local mode perform_later executes the job with perform_now instead.". This is annoying and messes with formatting of the test results. 
I replaced puts statement with Jets.logger.info which probably should be done in all other places, but I'm trying to keep this PR short and on point.
Run rspec of any project that calls job with `perform_later`. If you don't see a message "INFO: Not on AWS Lambda. In local mode perform_later executes the job with perform_now instead.", this PR's job is done.
=> Replace puts with Jets.logger.info in jobs

lib/jets/command.rb, lib/jets/command/base.rb, lib/jets/command/rake_decorate.rb
Improve the cli usage so that it provides a friendly error and usage message when user:
* provides invalid non-existent command 
* provides invalid options for the command
Had to jump through some hoops and decorate Rake::TaskManager in order to lazy load the commands for the help usage message without loading the Rails const.
N/A
These commands should sure friendly error and usage message
jets console --foo
jets foo:bar
Also, should do regression test and make sure other commands still work. Examples:
jets about
jets console
jets deploy
jets server
Patch
=> improve cli usage invalid command and options handling

lib/jets/commands/rollback/rollback_command.rb
- [x ] The test suite passes (run `bundle exec rspec` to verify this)
no longer need specific usage handling for rollback command
Related #684
Same testing notes as #684
Patch
=> rollback usage cleanup

lib/jets/builders/code_builder.rb
Allow jets applications to deploy without [sprockets-jets](https://github.com/rubyonjets/sprockets-jets). This can be useful for API projects that do not serve assets. This allows [jets deploy](https://docs.rubyonjets.com/reference/jets-deploy/) to work when users remove the `sprockets-jets` from their Gemfile because they don't need it.
Note: There's actual use-cases for API projects that do serve assets. Actually, I have an API app that serves javascript and stylesheet assets.  Going to leave the `sprockets-jets` in API mode for the `jets new --mode api` generator.
Related #681
Remove `sprockets-jets` from `Gemfile` and run:
jets deploy
Patch
=> remove need for sprockets-jets dependency

lib/jets/builders/code_builder.rb, lib/jets/cfn/upload.rb, lib/jets/generators/overrides/app/templates/Gemfile.tt
cache control default when sprockets-jets not installed
Do include sprockets-jets by default in the `jets new --mode api` generator. This allows jets avoids the `jets assets:compile` step. 
#686
jets new demo --mode api
cd demo
jets deploy
Patch
=> do not include sprockets-jets in new app generator for api mode

lib/jets/builders/handler_generator.rb
ensure shim handler generated
fix jets deploy for empty project
#692
See #692 
Patch
=> fix jets deploy for empty project

lib/jets/builders/code_builder.rb
Dont reconfigure webpacker unless used.
Patch
=> dont run reconfigure webpacker unless using

lib/jets/lambda/dsl.rb, lib/jets/stack/main/dsl/sqs.rb
Using `ref("my_tasks")` with a **String** does not camelize the logical id. Only **Symbol** are camelized. This results in the CloudFormation deploy failing with code like this:
app/jobs/waiter_job.rb
```ruby
class WaiterJob < ApplicationJob
depends_on "list"
class_timeout 30 # less than to equal to the default queue timeout
sqs_event ref("my_tasks")
def dig
puts "done digging"
end
end
```
app/shared/resources/list.rb
```ruby
class List < Jets::Stack
sqs_queue("my_tasks", message_retention_period: 3600, visibility_timeout: 120)
end
```
This adjusts the `ref` method so that it'll camelize String or Symbol, so the code above deploy successfully.
https://community.boltops.com/t/ruby-on-jets-5-0-release-improvements-galore/1123/6?u=tung
Deploy this project. …
=> fix sqs_queue output url camelcase name

lib/jets/job/dsl/dynamodb_event.rb, lib/jets/job/dsl/kinesis_event.rb, lib/jets/job/dsl/sqs_event.rb
Right now adding `iam_policy` will override the default policy that is associated with a Lambda Function handing an event.
IE: The SQS Event https://docs.rubyonjets.com/docs/events/sqs/
This feels like unexpected behavior. Instead, make the iam_policy **additive** to the default SQS IAM policy added by Jets.
Community Post: https://community.boltops.com/t/missing-sqs-messages/1126/3
Docs:
* https://docs.rubyonjets.com/docs/events/sqs/
* https://docs.rubyonjets.com/docs/events/kinesis/
* https://docs.rubyonjets.com/docs/events/dynamodb/
Example code snippet
app/jobs/courier_job.rb
```ruby
class CourierJob < ApplicationJob
include Jets::AwsServices
iam_policy("sns")
sqs_event ref(:waitlist)
def process
Jets.logger.info("test …
```
=> make iam_policy additive to default_iam_policy for event

lib/jets/stack/output/lookup.rb
Reduces CloudFormation API calls to avoid `Rate exceeded Aws::CloudFormation::Errors::Throttling`
https://community.boltops.com/t/store-shared-resource-name-store/766
Sanity check with `List.lookup(:waitlist_url)` example.
Patch
=> cache Stack.lookup output in class memory

lib/jets/generators/job/templates/event_types/s3.rb.tt, lib/jets/job/helpers/kinesis_event_helper.rb, lib/jets/job/helpers/log_event_helper.rb, lib/jets/job/helpers/s3_event_helper.rb, lib/jets/job/helpers/sns_event_helper.rb, lib/jets/job/helpers/sqs_event_helper.rb
Instead of `sqs_event_payload`, users should use `sqs_event_payloads`. The `sqs_event_payload` only grabs the first message. When there are rapid fire events, users can miss an event.
The old helpers like `sqs_event_payload` are deprecated with a warning.
Also add question mark helpers. IE: `sns_event_payloads?`
https://community.boltops.com/t/missing-sqs-messages/1126/15
Send events very fast. See forum thread and repo for reproduction:
* https://community.boltops.com/t/missing-sqs-messages/1126/15
* https://github.com/tongueroo/demo-sqs-courier
Patch
=> update s3 sns and sqs event helpers to return all events

lib/jets/job/helpers/s3_event_helper.rb, spec/lib/jets/job/base_spec.rb
Fix specs and rename method to `s3_event_payloads` to avoid conflict and also be consistent with other helpers.
https://github.com/rubyonjets/jets/pull/700
Run specs
Patch
=> fix s3_event and change method to s3_event_payloads

lib/jets/commands/application/application_command.rb
Show `jets --version` correctly when outside of Jets project. Right now it shows the rails components version 🤣
Related #703
Run `jets --version` outside of jets project.
Patch
=> fix jets --version outside of jets project

lib/jets/util/yamler.rb
Upgrading an older Jets app from jets 3 to jets 4 and Ruby 3.2.2, I ran into an error with deploying related to YAML.load_file of generated CloudFormation templates for my Jets controllers. Some of the data looked like a Date and was crashing with the following:
```
Psych::DisallowedClass: Tried to load unspecified class: Date
/Users/nate/.rbenv/versions/3.2.2/lib/ruby/3.2.0/psych/class_loader.rb:99:in `find'
/Users/nate/.rbenv/versions/3.2.2/lib/ruby/3.2.0/psych/class_loader.rb:28:in `load'
(eval):2:in `date'
```
This fixes the issue. I'm not sure what caused it to come up exactly, I'm guessing a gem dependency update.
=> permit YAML load of Date class

engines/internal/app/jobs/jets/preheat_job.rb, lib/jets/cfn/builder.rb, spec/lib/jets/cfn/builder_spec.rb, spec/lib/jets/internal/preheat_job_spec.rb
Fixes 3 issues with prewarming
1) The PreHeatJob is no longer included during stack build so prewarming never happens 
2) The PreHeatJob warm function was not scheduled with `rate` since the Jets 5 release
3) At the end of deploy the call to prewarm! has a spelling error and enqueues a :warn event instead of :warm
Prewarming was broken in Jets 5
Create a new Jets project and deploy it. Notice there is no lambda function for prewarming. Also notice at the end of the deployment it says prewarming but it actually does not trigger a call to warm.
5.0.10
=> Fix Prewarming

lib/jets/lambda/dsl/warnings.rb, spec/lib/jets/cfn/builder/job_spec.rb
Using class_iam_policy on Jobs works but prints out a warning which is intended for Controllers. This change allows PreHeatJob and ALL Jobs to use iam_class_policy.
The warning is REALLY useful for Controllers but unfortunately also warns for all Jobs except the PreheatJob.
Add `class_iam_policy` to any Job and when the Job class is loaded, notice you get a warning message. Or just run the job_spec.rb.
5.0.x (10 currently)
=> Remove iam_class_policy warning from Jobs

lib/jets/overrides/lambda/marshaller.rb
The Jets AWS Lambda Marshaller override messes up international characters. 
**Screenshot before fix:**
**Screenshot after fix:**
Thanks to Brazil based user report.
I don't exactly remember why I added the original force encoding. So removing it with a note.
Deploy test project that user provided
https://github.com/VictorCostaOliveira/jets-error-demo
To to the /posts path.
The international characters should be right.
Patch
=> remove force_encoding that causes issues for international characters

jets.gemspec, lib/jets/dotenv.rb
Fixes for Dotenv 3.0. Dotenv 3.0 made some breaking changes in order to make some good improvements. See it's changelog: https://github.com/bkeepers/dotenv/blob/main/Changelog.md
Users have reported this and have been able to workaround it by pinning dotenv to 2 See #712 
Also, there's a related PR #716 Totally get taking the approach to pin to lower versions. I've done it myself when there's a time-crunch.
This PR upgrades Jets so it works with the newer Dotenv 3.0 version and requires it. This will mean that users who have already pinned dotenv 2 in their Gemfile to remove it.
Eventually, found that older versions of gems become vaporware. Maintainers have other things in life than trying to keep old versions working 🤣
Some notes/thoughts about gem version pinning: …
=> fixes for dotenv 3.1

lib/jets/cfn/status.rb
This replaces a broken documentation link with a working link to a page covering the subject.
*NOTE:* I marked this as a documentation change as well as a bug fix because it's a change to an error message.
*NOTE:* I would mark the test suites as passing, but there are certain tests that fail for me even on master:
```
Failures:
1) Jets::Dotenv#load! ignores *.local files when JETS_ENV_REMOTE=1
Failure/Error: expect(env["ONLY_REMOTE"]).to eq "1"
expected: "1"
got: nil
(compared using ==)
2) Jets::Dotenv#load! replaces ssm:<relative-path> with SSM parameters prefixed with /<app-name>/<jets-env>/
Failure/Error: expect(env.fetch("AUTENTICATED_URL")).to eq value
KeyError:
key not found: "AUTENTICATED_URL"
3) Jets::Dotenv#load! replaces …
```
=> Update docs link in status.rb

engines/internal/app/jobs/jets/preheat_job.rb
* preheat invocation_type RequestResponse
Fixes the prewarming call post `jets deploy`.  Using `invocation_type: RequestResponse` so there's a `resp.payload` from the `resp = lambda_client.invoke` call.
Future versions of Jets uses a RequestResponse invocation time also because the extra resp.payload data is useful for printing and debugging.
Reported in the community forums https://community.boltops.com/t/cant-deploy-basic-api/1160/5
Go through one of the Jets learn guides
Patch
=> fix prewarming post deploy

lib/jets/generators/overrides/app/templates/config/environments/test.rb.tt
I need a little help getting this pull request up to snuff with the standards of this project because I'm editing a template used for the configuration of new apps. I'm not sure what sort of automated tests you want for something like this. Do you want me to try adding the config change that I've already added in the template to `spec/fixtures/demo/config/environments/test.rb`.
Also, while this pull request hasn't made any new tests fail for me, I also am strangely unable to get tests passing on master. I've included test results from master and from my branch for comparison purposes. I can create a support forum thread about this issue after creating this pull request, if you'd like. I'm running Ruby 3.2.3 on macOS 14.4.1 (23E224), and my master branch is currently …
=> Sets config.cache_classes to true in test env

lib/jets/cli.rb, lib/jets/cli/url.rb
Add `jets url --all` option. Don't show the deployed SQS queue urls by default.
https://community.boltops.com/t/1-sqs-queue-lambda-per-job/1189/3
Note: This does require upgrading `jets-rails` to at least 1.1.0
Related: https://github.com/rubyonjets/jets-rails/pull/14
Deploy multiple queues.
Patch
=> dont show queue url by default

lib/jets/cli/schedule/translate.rb
Support config/sidekiq.yml `scheduler.schedule` in for `jets scheduler:translate`
Patch
=> scheduler translate scheduler.schedule key

lib/jets/git/git_cli.rb
Super edge case, when the project has a `git init` repo but **no commits**  yet, it'll show some errors as Jets tries to get get git sha info that's unavailable. This fixes that.
Patch
=> git commit check

lib/jets/api/config.rb
When users are running `jets deploy` in a CI pipeline and they run `jets login $TOKEN` and TOKEN is not set, this provides a more helpful message.
Use a test script like this
prompt.sh
```sh
#!/usr/bin/env bash
exec jets login
```
Patch
=> jets login prompt message when likely ci env
